# Generated by Django 6.0.7 on 2026-07-25 12:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pupil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('device_id', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=120)),
                ('username', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': "o'quvchi",
                'verbose_name_plural': "o'quvchilar",
                'db_table': 'pupils',
            },
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('pupil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='progress', serialize=False, to='core.pupil')),
                ('state', models.JSONField(default=dict)),
                ('stars', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'progress',
            },
        ),
        migrations.CreateModel(
            name='LessonResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(default=0)),
                ('unit', models.IntegerField(default=0)),
                ('lesson', models.IntegerField(default=0)),
                ('lesson_name', models.CharField(blank=True, default='', max_length=120)),
                ('asked', models.IntegerField(default=0)),
                ('correct', models.IntegerField(default=0)),
                ('mistakes', models.IntegerField(default=0)),
                ('stars', models.IntegerField(default=0)),
                ('duration_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('pupil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.pupil')),
            ],
            options={
                'db_table': 'lesson_results',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['pupil', '-created_at'], name='lesson_resu_pupil_i_fd1c36_idx')],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('token_hash', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('platform', models.CharField(blank=True, default='', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('pupil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.pupil')),
            ],
            options={
                'db_table': 'sessions',
                'indexes': [models.Index(fields=['pupil'], name='sessions_pupil_i_c1a907_idx')],
            },
        ),
    ]
