# Generated by Django 6.0.7 on 2026-07-26 16:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_pupil_registered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='identity',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='KirishKodi',
            fields=[
                ('kod_hash', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('pupil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kirish_kodlari', to='core.pupil')),
            ],
            options={
                'verbose_name': 'kirish kodi',
                'verbose_name_plural': 'kirish kodlari',
                'db_table': 'kirish_kodlari',
                'indexes': [models.Index(fields=['pupil'], name='kirish_kodl_pupil_i_4b7ffa_idx')],
            },
        ),
    ]
