# Generated by Django 6.0.7 on 2026-07-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_progress_id_alter_identity_id_alter_profile_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupil',
            name='kanal_azo_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
