# Generated by Django 6.0.7 on 2026-07-29 09:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_liga'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupil',
            name='bot_bloklandi_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='Reklama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matn', models.TextField(blank=True, default='')),
                ('tugma', models.BooleanField(default=True)),
                ('tugma_matni', models.CharField(default="Aql Zone'ni ochish", max_length=64)),
                ('havola', models.CharField(blank=True, default='', max_length=300)),
                ('holat', models.CharField(choices=[('qoralama', 'hali yuborilmagan'), ('ketyapti', 'yuborilmoqda'), ('tugadi', 'hammaga yetdi'), ('toxtatildi', "qo'lda to'xtatilgan")], default='qoralama', max_length=12)),
                ('jami', models.IntegerField(default=0)),
                ('yuborildi', models.IntegerField(default=0)),
                ('bloklandi', models.IntegerField(default=0)),
                ('xato', models.IntegerField(default=0)),
                ('kim', models.CharField(blank=True, default='', max_length=40)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('boshlandi_at', models.DateTimeField(blank=True, null=True)),
                ('tugadi_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reklama',
                'indexes': [models.Index(fields=['-created_at'], name='reklama_created_d994df_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReklamaQabul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holat', models.CharField(choices=[('yuborildi', 'yetdi'), ('bloklandi', 'bot bloklangan'), ('xato', 'yuborilmadi')], max_length=12)),
                ('izoh', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('pupil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reklamalar', to='core.pupil')),
                ('reklama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qabullar', to='core.reklama')),
            ],
            options={
                'db_table': 'reklama_qabul',
                'indexes': [models.Index(fields=['reklama', 'holat'], name='reklama_qab_reklama_e70235_idx')],
                'constraints': [models.UniqueConstraint(fields=('reklama', 'pupil'), name='reklama_bir_odamga_bir_marta')],
            },
        ),
    ]
