# Generated by Django 6.0.7 on 2026-07-29 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_reklama'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupil',
            name='eslatma_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
