# Generated by Django 6.0.7 on 2026-07-30 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_pupil_eslatma_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupil',
            name='til',
            field=models.CharField(blank=True, default='uz', max_length=2),
        ),
    ]
