# Generated by Django 6.0.7 on 2026-07-31 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_pupil_til'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupil',
            name='qaytarish_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='pupil',
            name='qaytarish_soni',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pupil',
            name='xabar_yopiq_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
