# Generated by Django 6.0.7 on 2026-07-31 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_pupil_qaytarish_at_pupil_qaytarish_soni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reklama',
            name='tugma_rangi',
            field=models.CharField(blank=True, choices=[('success', 'yashil — asosiy harakat'), ('primary', "ko'k — yordamchi"), ('danger', 'qizil — ogohlantirish'), ('', "rangsiz — mijozning o'z ko'rinishi")], default='success', max_length=10),
        ),
    ]
