# Generated by Django 6.0.7 on 2026-07-31 20:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_reklama_tugma_rangi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=16, unique=True)),
                ('urug', models.BigIntegerField()),
                ('oyin', models.CharField(max_length=16)),
                ('daraja', models.SmallIntegerField(default=2)),
                ('chaqirgan_ball', models.IntegerField(default=0)),
                ('chaqirgan_xato', models.IntegerField(default=0)),
                ('chaqirgan_sanoq', models.JSONField(default=list)),
                ('chaqirgan_tugatdi', models.BooleanField(default=False)),
                ('qabul_ball', models.IntegerField(default=0)),
                ('qabul_xato', models.IntegerField(default=0)),
                ('qabul_sanoq', models.JSONField(default=list)),
                ('qabul_tugatdi', models.BooleanField(default=False)),
                ('golib', models.CharField(blank=True, default='', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tugadi_at', models.DateTimeField(blank=True, null=True)),
                ('chaqirgan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yuborgan_duellar', to='core.profile')),
                ('qabul', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qabul_duellar', to='core.profile')),
            ],
            options={
                'db_table': 'duel',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='duel_created_a82ee3_idx'), models.Index(fields=['chaqirgan', '-created_at'], name='duel_chaqirg_aecf5d_idx')],
            },
        ),
    ]
