# Generated by Django 6.0.7 on 2026-08-01 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_duel'),
    ]

    operations = [
        migrations.AddField(
            model_name='duel',
            name='boshlanadi',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='duel',
            name='chaqirgan_belgi',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='duel',
            name='chaqirgan_tayyor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='duel',
            name='qabul_belgi',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='duel',
            name='qabul_tayyor',
            field=models.BooleanField(default=False),
        ),
    ]
