# Generated by Django 6.0.7 on 2026-08-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_duel_jonli'),
    ]

    operations = [
        migrations.AddField(
            model_name='duel',
            name='savollar_soni',
            field=models.SmallIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='duel',
            name='vaqt',
            field=models.SmallIntegerField(default=60),
        ),
    ]
