# Generated by Django 6.0.7 on 2026-08-26 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_duel_yana'),
    ]

    operations = [
        migrations.CreateModel(
            name='Masala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sinf', models.SmallIntegerField(default=0)),
                ('matn', models.TextField(max_length=2000)),
                ('javob', models.CharField(max_length=100)),
                ('yechim', models.TextField(max_length=4000)),
                ('holat', models.CharField(choices=[('kutmoqda', 'Kutmoqda'), ('tasdiq', 'Tasdiqlangan'), ('rad', 'Rad etilgan')], default='kutmoqda', max_length=10)),
                ('rad_sababi', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('korilgan_at', models.DateTimeField(blank=True, null=True)),
                ('urinish_soni', models.IntegerField(default=0)),
                ('yechgan_soni', models.IntegerField(default=0)),
                ('like_soni', models.IntegerField(default=0)),
                ('dislike_soni', models.IntegerField(default=0)),
                ('muallif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masalalar', to='core.profile')),
            ],
            options={
                'db_table': 'masala',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MasalaMukofot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanga', models.IntegerField(default=0)),
                ('jami', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='masala_mukofoti', to='core.profile')),
            ],
            options={
                'db_table': 'masala_mukofot',
            },
        ),
        migrations.CreateModel(
            name='MasalaOvoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tur', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('masala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ovozlar', to='core.masala')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masala_ovozlari', to='core.profile')),
            ],
            options={
                'db_table': 'masala_ovoz',
            },
        ),
        migrations.CreateModel(
            name='MasalaUrinish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('togri', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('masala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urinishlar', to='core.masala')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masala_urinishlari', to='core.profile')),
            ],
            options={
                'db_table': 'masala_urinish',
            },
        ),
        migrations.AddIndex(
            model_name='masala',
            index=models.Index(fields=['holat', '-created_at'], name='masala_holat_fc7f6f_idx'),
        ),
        migrations.AddIndex(
            model_name='masala',
            index=models.Index(fields=['holat', 'sinf'], name='masala_holat_5c738b_idx'),
        ),
        migrations.AddIndex(
            model_name='masala',
            index=models.Index(fields=['muallif', 'holat'], name='masala_muallif_f5690e_idx'),
        ),
        migrations.AddConstraint(
            model_name='masalaovoz',
            constraint=models.UniqueConstraint(fields=('masala', 'profile'), name='masala_bir_odam_bir_ovoz'),
        ),
        migrations.AddConstraint(
            model_name='masalaurinish',
            constraint=models.UniqueConstraint(fields=('masala', 'profile'), name='masala_bir_odam_bir_urinish'),
        ),
    ]
