# Generated by Django 6.0.7 on 2026-08-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_masalalar'),
    ]

    operations = [
        migrations.AddField(
            model_name='masala',
            name='muallif_tanga',
            field=models.IntegerField(default=0),
        ),
    ]
