# Generated by Django 6.0.7 on 2026-08-27 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_masala_muallif_tanga'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masala',
            name='muallif_tanga',
        ),
        migrations.DeleteModel(
            name='MasalaMukofot',
        ),
    ]
