# Generated by Django 6.0.7 on 2026-08-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_masala_tangasiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='masala',
            name='rasm',
            field=models.ImageField(blank=True, null=True, upload_to='masala/%Y/%m/'),
        ),
    ]
