# Generated by Django 6.0.7 on 2026-09-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_masala_rasm'),
    ]

    operations = [
        migrations.AddField(
            model_name='masala',
            name='kanal_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
