# Generated by Django 6.0.7 on 2026-09-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_masala_kanal_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='masala',
            name='kanal_post_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
