# Generated by Django 6.0.7 on 2026-09-07 16:54

from django.db import migrations, models


def eskilarni_och(apps, schema_editor):
    """
    Eski urinishlarda yechim ALLAQACHON ochilgan edi.

    Yangi qoidagacha yechim bitta urinishdan keyin ko'rinardi. Ya'ni
    bu jadvaldagi har bir odam yechimni o'z ekranida ko'rgan. Maydon
    `False` bo'lib qolsa, ular ertaga ilovani ochganda yechim
    yo'qolgan bo'lardi — o'zlari hech narsa qilmagan holda.
    """
    apps.get_model("core", "MasalaUrinish").objects.update(yechim_ochiq=True)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_masala_kanal_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='masalaurinish',
            name='soni',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='masalaurinish',
            name='yechim_ochiq',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(eskilarni_och, migrations.RunPython.noop),
    ]
