# Generated by Django 6.0.7 on 2026-09-08 04:44

from django.db import migrations, models


def eskilarni_belgila(apps, schema_editor):
    """
    Ro'yxatdan o'tgan eski hisoblar tilni ALLAQACHON tanlagan.

    Ular ilovaga kirgan, ekranda tilni ko'rgan va undan foydalangan.
    Bayroq `False` bo'lib qolsa, birinchi ochilishda ulardan tilni
    yana so'rardik — ya'ni tuzatish o'zi muammo yasardi.

    Ro'yxatdan o'tmagan hisoblarga tegilmaydi: ular haqiqatan
    so'ralmagan bo'lishi mumkin.
    """
    apps.get_model("core", "Pupil").objects.exclude(
        registered_at=None,
    ).update(til_tanlandi=True)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_masalaurinish_soni_masalaurinish_yechim_ochiq'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupil',
            name='til_tanlandi',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(eskilarni_belgila, migrations.RunPython.noop),
    ]
