# Generated by Django 6.0.7 on 2026-09-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_pupil_til_tanlandi'),
    ]

    operations = [
        migrations.AddField(
            model_name='masala',
            name='kanal_tekshir_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masala',
            name='kanal_yoq',
            field=models.BooleanField(default=False),
        ),
    ]
