# Generated by Django 6.0.7 on 2026-09-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_masala_kanal_tekshir_at_masala_kanal_yoq'),
    ]

    operations = [
        migrations.AddField(
            model_name='masala',
            name='variantlar',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
