# Generated by Django 6.0.7 on 2026-09-08 17:41

import django.db.models.deletion
from django.db import migrations, models


def eskilarni_belgila(apps, schema_editor):
    """
    Eski urinishlarga `yechdi` ni qo'yadi.

    Bizda faqat BIRINCHI urinish natijasi saqlangan (`togri`), ya'ni
    "ikkinchi urinishda topdimi?" degan savolga javob beradigan
    ma'lumot umuman yo'q. Shuning uchun eng ehtiyotkor tanlov:
    birinchi urinishda topganlar — yechgan, qolganlari esa yangi
    javob berguncha "yecholmagan" bo'lib qoladi.

    Aksincha qilish — yechim ochilganlarning hammasini "yechgan" deb
    belgilash — noto'g'ri bo'lardi: yechim tanga evaziga ham,
    uchta xato urinishdan keyin ham ochiladi.
    """
    apps.get_model("core", "MasalaUrinish").objects.filter(togri=True).update(yechdi=True)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_masala_variantlar'),
    ]

    operations = [
        migrations.AddField(
            model_name='masala',
            name='korish_soni',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='masalaurinish',
            name='yechdi',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MasalaKorish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('masala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='korishlar', to='core.masala')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masala_korishlari', to='core.profile')),
            ],
            options={
                'db_table': 'masala_korish',
                'constraints': [models.UniqueConstraint(fields=('masala', 'profile'), name='masala_bir_odam_bir_korish')],
            },
        ),
        migrations.RunPython(eskilarni_belgila, migrations.RunPython.noop),
    ]
