# Generated by Django 6.0.7 on 2026-09-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_masala_korish_soni_masalaurinish_yechdi_masalakorish'),
    ]

    operations = [
        migrations.AddField(
            model_name='masala',
            name='kanal_sanoq',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
