# Generated by Django 6.0.7 on 2026-09-10 14:29

from django.db import migrations, models


def raqamlarni_ber(apps, schema_editor):
    """
    Mavjud masalalarga 1 dan boshlab raqam beradi.

    Tartib — YARATILGAN VAQT bo'yicha, `pk` bo'yicha emas. Amalda
    ikkalasi bir xil, lekin ma'nosi boshqa: raqam "nechanchi bo'lib
    qo'shilgan" degan savolga javob beradi va ro'yxatning o'z
    tartibi ham shunga quriladi ("Yangi").

    Ilgari ekranda `pk` turardi va unda teshiklar bor edi: bitta
    masala o'chirilgani uchun o'n beshta masala "2 dan 16 gacha"
    bo'lib ko'rinardi.
    """
    Masala = apps.get_model("core", "Masala")
    for n, m in enumerate(Masala.objects.order_by("created_at", "pk"), start=1):
        Masala.objects.filter(pk=m.pk).update(raqam=n)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_masala_kanal_sanoq'),
    ]

    operations = [
        migrations.AddField(
            model_name='masala',
            name='raqam',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.RunPython(raqamlarni_ber, migrations.RunPython.noop),
    ]
