# Generated by Django 6.0.6 on 2026-09-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_masala_raqam'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupil',
            name='ustoz',
            field=models.BooleanField(default=False),
        ),
    ]
