# Generated by Django 6.0.6 on 2026-09-12 18:42

from django.db import migrations, models
from django.db.models import Count, Q


def sanoqni_tikla(apps, schema_editor):
    """
    Mavjud masalalarga oxir-oqibat yechganlar sonini yozadi.

    Usiz maydon nolda qolardi va bo'lim birdan "hech kim
    yechmagan" deb ko'rsatardi — ma'lumot esa `MasalaUrinish` da
    joyida turibdi (`yechdi` bayrog'i).

    `bulk_update` bilan: o'n beshta masalaga o'n beshta alohida
    `UPDATE` yuborishning hojati yo'q.
    """
    Masala = apps.get_model("core", "Masala")
    qator = list(
        Masala.objects.annotate(
            hisob=Count("urinishlar", filter=Q(urinishlar__yechdi=True)),
        )
    )
    for m in qator:
        m.yechdi_soni = m.hisob
    if qator:
        Masala.objects.bulk_update(qator, ["yechdi_soni"], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_pupil_ustoz'),
    ]

    operations = [
        migrations.AddField(
            model_name='masala',
            name='yechdi_soni',
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(sanoqni_tikla, migrations.RunPython.noop),
    ]
