# Generated by Django 6.0.6 on 2026-09-14 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_masalaurinish_yechdi_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestToplam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raqam', models.IntegerField(unique=True)),
                ('sinf', models.SmallIntegerField()),
                ('nom', models.CharField(max_length=80)),
                ('urug', models.BigIntegerField()),
                ('savol_soni', models.SmallIntegerField(default=15)),
                ('daqiqa', models.SmallIntegerField(default=20)),
                ('faol', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ishlagan_soni', models.IntegerField(default=0)),
                ('togri_jami', models.IntegerField(default=0)),
                ('kanal_at', models.DateTimeField(blank=True, null=True)),
                ('kanal_post_id', models.IntegerField(blank=True, null=True)),
                ('kanal_yoq', models.BooleanField(default=False)),
                ('kanal_tekshir_at', models.DateTimeField(blank=True, null=True)),
                ('kanal_sanoq', models.CharField(blank=True, default='', max_length=40)),
            ],
            options={
                'db_table': 'test_toplam',
                'ordering': ['sinf', 'raqam'],
            },
        ),
        migrations.CreateModel(
            name='TestIshlash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('togri', models.SmallIntegerField()),
                ('jami', models.SmallIntegerField()),
                ('sekund', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_ishlashlari', to='core.profile')),
                ('toplam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ishlashlar', to='core.testtoplam')),
            ],
            options={
                'db_table': 'test_ishlash',
                'indexes': [models.Index(fields=['toplam', 'togri'], name='test_ishlas_toplam__e63f35_idx')],
                'constraints': [models.UniqueConstraint(fields=('toplam', 'profile'), name='toplam_bir_odam_bir_natija')],
            },
        ),
    ]
