# Generated by Django 6.0.6 on 2026-09-14 16:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_test_toplam_boshlangich'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faollik',
            fields=[
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='faollik', serialize=False, to='core.profile')),
                ('joy', models.CharField(choices=[('dars', 'Dars'), ('blok', 'Blok test'), ('toplam', "Test to'plami"), ('masala', 'Masala')], max_length=10)),
                ('nom', models.CharField(blank=True, default='', max_length=120)),
                ('savol', models.SmallIntegerField(default=0)),
                ('jami', models.SmallIntegerField(default=0)),
                ('togri', models.SmallIntegerField(default=0)),
                ('boshlandi', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'faollik',
            },
        ),
    ]
