# Generated by Django 6.0.7 on 2026-09-16 13:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_faollik'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupil',
            name='anketa_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='pupil',
            name='anketa_sinf',
            field=models.SmallIntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='pupil',
            name='kim',
            field=models.CharField(blank=True, choices=[('oquvchi', "O'quvchi"), ('ota_ona', 'Ota-ona'), ('ustoz', 'Ustoz')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='pupil',
            name='qurilma',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AddField(
            model_name='pupil',
            name='tg_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pupil',
            name='viloyat',
            field=models.CharField(blank=True, default='', max_length=24),
        ),
        migrations.CreateModel(
            name='Hodisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tur', models.CharField(choices=[('sahifa', 'Sahifa'), ('bosish', 'Bosish')], max_length=8)),
                ('yol', models.CharField(blank=True, default='', max_length=80)),
                ('nom', models.CharField(blank=True, default='', max_length=48)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('pupil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hodisalar', to='core.pupil')),
            ],
            options={
                'db_table': 'hodisa',
                'indexes': [models.Index(fields=['pupil', 'created_at'], name='hodisa_pupil_i_9613bf_idx')],
            },
        ),
    ]
