# Generated by Django 6.0.7 on 2026-09-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_tahlil_anketa'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupil',
            name='yozish_ruxsat_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='hodisa',
            name='tur',
            field=models.CharField(choices=[('kirish', 'Kirish'), ('sahifa', 'Sahifa'), ('bosish', 'Bosish')], max_length=8),
        ),
    ]
