# Generated by Django 6.0.7 on 2026-09-16 19:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_ushlash'),
    ]

    operations = [
        migrations.AddField(
            model_name='duel',
            name='chaqirgan_daraja',
            field=models.SmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='duel',
            name='kimga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kelgan_duellar', to='core.profile'),
        ),
        migrations.AddField(
            model_name='duel',
            name='qabul_daraja',
            field=models.SmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='profile',
            name='taklif_yopiq',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DuelTaklif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holat', models.CharField(choices=[('kutyapti', 'kutyapti'), ('qabul', 'qabul'), ('rad', 'rad')], default='kutyapti', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('javob_at', models.DateTimeField(blank=True, null=True)),
                ('duel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='takliflar', to='core.duel')),
                ('kimdan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yuborgan_takliflar', to='core.profile')),
                ('kimga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kelgan_takliflar', to='core.profile')),
            ],
            options={
                'db_table': 'duel_taklif',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['kimga', '-created_at'], name='duel_taklif_kimga_i_75524f_idx'), models.Index(fields=['kimdan', 'kimga', '-created_at'], name='duel_taklif_kimdan__6cad9f_idx')],
            },
        ),
    ]
