# Generated by Django 6.0.7 on 2026-09-17 03:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_duel_adolat_taklif'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(db_index=True, max_length=8)),
                ('oyin', models.CharField(choices=[('kartalar', 'Son kartalari'), ('royale', 'Hisob Royale'), ('kodlar', 'Son kodlari')], max_length=12)),
                ('holat', models.CharField(choices=[('kutish', 'kutish'), ('oyin', 'oyin'), ('tugadi', 'tugadi')], default='kutish', max_length=8)),
                ('davlat', models.JSONField(blank=True, default=dict)),
                ('gaplar', models.JSONField(blank=True, default=list)),
                ('raund', models.SmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('boshlandi_at', models.DateTimeField(blank=True, null=True)),
                ('tugadi_at', models.DateTimeField(blank=True, null=True)),
                ('egasi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xonalar', to='core.profile')),
            ],
            options={
                'db_table': 'xona',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='XonaAzo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robot', models.BooleanField(default=False)),
                ('ism', models.CharField(default='', max_length=40)),
                ('avatar', models.CharField(blank=True, default='', max_length=40)),
                ('daraja', models.SmallIntegerField(default=2)),
                ('tayyor', models.BooleanField(default=False)),
                ('belgi', models.DateTimeField(default=django.utils.timezone.now)),
                ('joy', models.SmallIntegerField(default=0)),
                ('chiqdi', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='xona_azoliklari', to='core.profile')),
                ('xona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='azolar', to='core.xona')),
            ],
            options={
                'db_table': 'xona_azo',
                'ordering': ['joy', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='KartaKolleksiya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kalit', models.CharField(max_length=16)),
                ('soni', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kartalar', to='core.profile')),
            ],
            options={
                'db_table': 'karta_kolleksiya',
                'constraints': [models.UniqueConstraint(fields=('profile', 'kalit'), name='karta_kolleksiya_yagona')],
            },
        ),
        migrations.AddIndex(
            model_name='xona',
            index=models.Index(fields=['kod', '-created_at'], name='xona_kod_8201c4_idx'),
        ),
    ]
