# Generated by Django 6.0.7 on 2026-09-17 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_jamoaviy_xonalar'),
    ]

    operations = [
        migrations.AddField(
            model_name='xona',
            name='boshlanish',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='xona',
            name='kutish_soniya',
            field=models.SmallIntegerField(default=120),
        ),
        migrations.AddField(
            model_name='xona',
            name='ochiq',
            field=models.BooleanField(default=False),
        ),
    ]
