# Generated by Django 6.0.7 on 2026-09-17 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_ochiq_xona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xona',
            name='oyin',
            field=models.CharField(choices=[('kartalar', 'Son kartalari'), ('royale', 'Hisob Royale'), ('kodlar', 'Son kodlari'), ('seyf', 'Seyf')], max_length=12),
        ),
    ]
