# Generated by Django 6.0.7 on 2026-09-17 17:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_seyf'),
    ]

    operations = [
        migrations.CreateModel(
            name='OyinchiTajriba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ochko', models.IntegerField(default=0)),
                ('oyinlar', models.IntegerField(default=0)),
                ('galabalar', models.IntegerField(default=0)),
                ('xoin_topdi', models.IntegerField(default=0)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tajriba', to='core.profile')),
            ],
            options={
                'db_table': 'oyinchi_tajriba',
            },
        ),
        migrations.CreateModel(
            name='Shaharcha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binolar', models.JSONField(blank=True, default=dict)),
                ('hosil_kun', models.DateField(blank=True, null=True)),
                ('yurak', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shaharcha', to='core.profile')),
            ],
            options={
                'db_table': 'shaharcha',
            },
        ),
        migrations.CreateModel(
            name='ShaharchaYoqdi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kun', models.DateField()),
                ('kimdan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.profile')),
                ('kimga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.profile')),
            ],
            options={
                'db_table': 'shaharcha_yoqdi',
                'constraints': [models.UniqueConstraint(fields=('kimdan', 'kimga', 'kun'), name='shaharcha_yoqdi_kuniga')],
            },
        ),
        migrations.CreateModel(
            name='XonaNatija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oyin', models.CharField(max_length=12)),
                ('ochko', models.IntegerField(default=0)),
                ('golib', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xona_natijalari', to='core.profile')),
                ('xona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='natijalar', to='core.xona')),
            ],
            options={
                'db_table': 'xona_natija',
                'indexes': [models.Index(fields=['-created_at'], name='xona_natija_created_20cee8_idx'), models.Index(fields=['profile', '-created_at'], name='xona_natija_profile_3b2e08_idx')],
            },
        ),
    ]
