# Generated by Django 6.0.7 on 2026-09-19 15:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_tajriba_shaharcha'),
    ]

    operations = [
        migrations.CreateModel(
            name='KarvonHolat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bekat', models.SmallIntegerField(default=0)),
                ('yulduz', models.SmallIntegerField(default=0)),
                ('daraja', models.SmallIntegerField(default=2)),
                ('faol_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='karvon', to='core.profile')),
            ],
            options={
                'db_table': 'karvon_holat',
                'indexes': [models.Index(fields=['-bekat', '-yulduz'], name='karvon_hola_bekat_3c9f40_idx')],
            },
        ),
    ]
