# Generated by Django 6.0.7 on 2026-09-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_karvon_holat'),
    ]

    operations = [
        migrations.AddField(
            model_name='karvonholat',
            name='joriy',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='karvonholat',
            name='yulduzlar',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
