# Generated by Django 6.0.7 on 2026-09-20 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_karvon_server'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='karvonholat',
            name='karvon_hola_bekat_3c9f40_idx',
        ),
        migrations.AddField(
            model_name='karvonholat',
            name='mavsum',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='karvonholat',
            name='otgan_yulduz',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='karvonholat',
            index=models.Index(fields=['-mavsum', '-bekat', '-yulduz'], name='karvon_hola_mavsum_13f9bf_idx'),
        ),
    ]
