# Generated by Django 6.0.7 on 2026-09-20 15:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_remove_karvonholat_karvon_hola_bekat_3c9f40_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KunlikSonNatija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField()),
                ('daraja', models.SmallIntegerField()),
                ('urinish', models.SmallIntegerField(default=0)),
                ('bajardi', models.BooleanField(default=False)),
                ('sekund', models.IntegerField(default=0)),
                ('urinishlar', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kunlik_son', to='core.profile')),
            ],
            options={
                'db_table': 'kunlik_son_natija',
                'indexes': [models.Index(fields=['sana', 'bajardi'], name='kunlik_son__sana_199bc6_idx'), models.Index(fields=['profile', '-sana'], name='kunlik_son__profile_7a71f6_idx')],
                'constraints': [models.UniqueConstraint(fields=('profile', 'sana', 'daraja'), name='kunlik_son_bir_kun')],
            },
        ),
    ]
