# Generated by Django 6.0.7 on 2026-09-25 02:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_kunliksonnatija'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImtihonNatija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.SmallIntegerField()),
                ('togri', models.SmallIntegerField()),
                ('jami', models.SmallIntegerField()),
                ('sekund', models.IntegerField(default=0)),
                ('mijoz_vaqt', models.BigIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imtihon_natijalari', to='core.profile')),
            ],
            options={
                'db_table': 'imtihon_natija',
                'indexes': [models.Index(fields=['profile', '-mijoz_vaqt'], name='imtihon_nat_profile_b07cc8_idx')],
                'constraints': [models.UniqueConstraint(fields=('profile', 'mijoz_vaqt'), name='imtihon_bir_urinish')],
            },
        ),
    ]
