# Generated by Django 6.0.7 on 2026-09-25 15:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_imtihonnatija'),
    ]

    operations = [
        migrations.CreateModel(
            name='KanalYozuv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tur', models.CharField(choices=[('yangilik', 'Yangilik'), ('fakt', 'Fakt'), ('misol', 'Misol')], max_length=10)),
                ('kalit', models.CharField(max_length=300, unique=True)),
                ('sarlavha', models.CharField(blank=True, default='', max_length=300)),
                ('matn', models.TextField(blank=True, default='')),
                ('manba', models.CharField(blank=True, default='', max_length=40)),
                ('topilgan_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('joylangan_at', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'kanal_yozuv',
                'indexes': [models.Index(fields=['tur', 'joylangan_at'], name='kanal_yozuv_tur_4b2183_idx')],
            },
        ),
    ]
