# Generated by Django 6.0.7 on 2026-09-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_kanalyozuv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faollik',
            name='joy',
            field=models.CharField(choices=[('dars', 'Dars'), ('blok', 'Blok test'), ('toplam', "Test to'plami"), ('masala', 'Masala'), ('oyin', "O'yin"), ('duel', 'Duel')], max_length=10),
        ),
    ]
