# Generated by Django 6.0.7 on 2026-09-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_faollik_oyin'),
    ]

    operations = [
        migrations.AddField(
            model_name='imtihonnatija',
            name='kurs',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='pupil',
            name='yonalish',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
    ]
