# Generated by Django 6.0.7 on 2026-09-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_yonalish_sessiya'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dueltaklif',
            name='holat',
            field=models.CharField(choices=[('kutyapti', 'kutyapti'), ('qabul', 'qabul'), ('rad', 'rad'), ('bekor', 'bekor')], default='kutyapti', max_length=10),
        ),
    ]
