# Generated by Django 5.2.17 on 2026-09-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0054_duel_taklif_bekor"),
    ]

    operations = [
        migrations.AddField(
            model_name="pupil",
            name="haftalik_hisobot",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pupil",
            name="hisobot_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
