# Generated by Django 5.2.17 on 2026-09-26 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0055_haftalik_hisobot"),
    ]

    operations = [
        migrations.CreateModel(
            name="MasalaIzoh",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matn", models.CharField(max_length=300)),
                (
                    "holat",
                    models.CharField(
                        choices=[
                            ("kutmoqda", "Kutmoqda"),
                            ("tasdiq", "Tasdiqlangan"),
                            ("rad", "Rad etilgan"),
                        ],
                        db_index=True,
                        default="kutmoqda",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "masala",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="izohlar",
                        to="core.masala",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="masala_izohlari",
                        to="core.profile",
                    ),
                ),
            ],
            options={
                "db_table": "masala_izoh",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["masala", "holat"],
                        name="masala_izoh_masala__90897c_idx",
                    )
                ],
            },
        ),
    ]
