# Generated by Django 6.0.7 on 2026-09-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_masala_izoh'),
    ]

    operations = [
        migrations.AddField(
            model_name='imtihonnatija',
            name='ball',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imtihonnatija',
            name='tur',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddIndex(
            model_name='imtihonnatija',
            index=models.Index(fields=['tur', 'kurs', 'created_at'], name='imtihon_nat_tur_a9258d_idx'),
        ),
    ]
