# Generated by Django 6.0.7 on 2026-09-28 17:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_imtihon_sertifikat_reyting'),
    ]

    operations = [
        migrations.CreateModel(
            name='KunlikOsish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField(unique=True)),
                ('kanal_azo', models.IntegerField(blank=True, null=True)),
                ('hisoblar', models.IntegerField(default=0)),
                ('yangi', models.IntegerField(default=0)),
                ('faol', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'kunlik_osish',
                'ordering': ['-sana'],
            },
        ),
        migrations.CreateModel(
            name='BotHodisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField()),
                ('tur', models.CharField(max_length=16)),
                ('manba', models.CharField(blank=True, default='', max_length=24)),
                ('n', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'bot_hodisa',
                'constraints': [models.UniqueConstraint(fields=('sana', 'tur', 'manba'), name='bot_hodisa_bir')],
            },
        ),
    ]
