# Generated by Django 6.0.7 on 2026-09-28 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_osish_tahlili'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupil',
            name='taklif_qilgan',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taklif_qilinganlar', to='core.pupil'),
        ),
    ]
