# Generated by Django 6.0.7 on 2026-09-28 17:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_taklif'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marafon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80)),
                ('boshlanish', models.DateField()),
                ('kunlar', models.SmallIntegerField(default=30)),
                ('savol', models.SmallIntegerField(default=10)),
                ('daqiqa', models.SmallIntegerField(default=20)),
                ('elon_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'marafon',
                'ordering': ['-boshlanish'],
            },
        ),
        migrations.AddField(
            model_name='imtihonnatija',
            name='mavzular',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='Sinf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60)),
                ('kod', models.CharField(max_length=8, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ustoz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sinflar', to='core.pupil')),
            ],
            options={
                'db_table': 'sinf',
            },
        ),
        migrations.CreateModel(
            name='MarafonNatija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kun', models.SmallIntegerField()),
                ('togri', models.SmallIntegerField()),
                ('jami', models.SmallIntegerField()),
                ('sekund', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('marafon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='natijalar', to='core.marafon')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marafon_natijalari', to='core.profile')),
            ],
            options={
                'db_table': 'marafon_natija',
                'constraints': [models.UniqueConstraint(fields=('marafon', 'profile', 'kun'), name='marafon_kun_bir')],
            },
        ),
        migrations.CreateModel(
            name='SinfAzo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qoshildi_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sinf_azoliklari', to='core.profile')),
                ('sinf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='azolar', to='core.sinf')),
            ],
            options={
                'db_table': 'sinf_azo',
                'constraints': [models.UniqueConstraint(fields=('sinf', 'profile'), name='sinf_azo_bir')],
            },
        ),
    ]
