# Generated by Django 6.0.6 on 2026-10-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_sinf_marafon'),
    ]

    operations = [
        migrations.AddField(
            model_name='kunlikosish',
            name='instagram_azo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kunlikosish',
            name='instagram_korish',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kunlikosish',
            name='instagram_qamrov',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
