# Generated by Django 6.0.7 on 2026-10-09 10:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_kunlikosish_instagram_azo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupil',
            name='premium_eslatildi',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='pupil',
            name='premium_gacha',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='pupil',
            name='premium_sinov_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='PremiumTolov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarif', models.CharField(choices=[('7kun', '7 kun'), ('1oy', '1 oy'), ('3oy', '3 oy')], max_length=4)),
                ('summa', models.IntegerField(default=0)),
                ('chek', models.CharField(blank=True, default='', max_length=255)),
                ('holat', models.CharField(choices=[('kutilmoqda', 'kutilmoqda'), ('tasdiqlandi', 'tasdiqlandi'), ('rad', 'rad etildi')], default='kutilmoqda', max_length=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('hal_qilingan_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('pupil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_tolovlar', to='core.pupil')),
            ],
            options={
                'db_table': 'premium_tolov',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['holat', 'created_at'], name='premium_tol_holat_a78d41_idx')],
            },
        ),
    ]
