# Generated by Django 6.0.7 on 2026-10-09 13:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_premium'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiSuhbat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tur', models.CharField(choices=[('xato', 'xatoni tushuntirish'), ('reja', 'zaif mavzular rejasi'), ('repetitor', 'repetitor'), ('masala', 'masala yechimi')], max_length=10)),
                ('manba', models.CharField(choices=[('ilova', 'ilova'), ('bot', 'bot')], default='ilova', max_length=5)),
                ('sarlavha', models.CharField(blank=True, default='', max_length=120)),
                ('kontekst', models.JSONField(blank=True, default=dict)),
                ('rasm', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('yangilangan_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('pupil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_suhbatlar', to='core.pupil')),
            ],
            options={
                'db_table': 'ai_suhbat',
                'ordering': ['-yangilangan_at'],
            },
        ),
        migrations.CreateModel(
            name='AiXabar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('user', 'odam'), ('ai', 'AI')], max_length=4)),
                ('matn', models.TextField(blank=True, default='')),
                ('holat', models.CharField(choices=[('kutilmoqda', 'kutilmoqda'), ('tayyor', 'tayyor'), ('xato', 'xato')], default='tayyor', max_length=10)),
                ('kirish_token', models.IntegerField(default=0)),
                ('chiqish_token', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('pupil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_xabarlar', to='core.pupil')),
                ('suhbat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xabarlar', to='core.aisuhbat')),
            ],
            options={
                'db_table': 'ai_xabar',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='aisuhbat',
            index=models.Index(fields=['pupil', 'yangilangan_at'], name='ai_suhbat_pupil_i_fb3c0d_idx'),
        ),
        migrations.AddIndex(
            model_name='aixabar',
            index=models.Index(fields=['rol', 'created_at'], name='ai_xabar_rol_2e0994_idx'),
        ),
        migrations.AddIndex(
            model_name='aixabar',
            index=models.Index(fields=['pupil', 'rol', 'created_at'], name='ai_xabar_pupil_i_0484b0_idx'),
        ),
    ]
