# Generated by Django 6.0.6 on 2026-10-09 14:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_ai_ustoz'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupil',
            name='kun_savoli_yopiq_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='KunSavoli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField()),
                ('daraja', models.CharField(max_length=24)),
                ('savol', models.TextField()),
                ('variantlar', models.JSONField(default=list)),
                ('togri', models.SmallIntegerField(default=0)),
                ('usul', models.TextField(blank=True, default='')),
                ('file_id', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'kun_savoli',
                'constraints': [models.UniqueConstraint(fields=('sana', 'daraja'), name='kun_savoli_bir')],
            },
        ),
        migrations.CreateModel(
            name='KunSavoliJavob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.CharField(max_length=32)),
                ('xabar_id', models.BigIntegerField(default=0)),
                ('holat', models.CharField(default='yuborildi', max_length=10)),
                ('javob', models.SmallIntegerField(blank=True, default=None, null=True)),
                ('togri', models.BooleanField(blank=True, default=None, null=True)),
                ('yuborilgan_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('javob_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('pupil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kun_savollari', to='core.pupil')),
                ('savol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='javoblar', to='core.kunsavoli')),
            ],
            options={
                'db_table': 'kun_savoli_javob',
                'indexes': [models.Index(fields=['yuborilgan_at'], name='kun_savoli__yuboril_a7fd8a_idx')],
                'constraints': [models.UniqueConstraint(fields=('savol', 'pupil'), name='kun_savoli_bir_odam')],
            },
        ),
        migrations.CreateModel(
            name='XatoXabar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manba', models.CharField(default='ilova', max_length=8)),
                ('joy', models.CharField(blank=True, default='', max_length=160)),
                ('kalit', models.CharField(blank=True, default='', max_length=80)),
                ('sabab', models.CharField(choices=[('javob', "Javob noto'g'ri"), ('variant', "To'g'ri javob variantlarda yo'q"), ('savol', 'Savol xato yozilgan'), ('korinish', "Ko'rinishi buzilgan"), ('boshqa', 'Boshqa')], default='boshqa', max_length=10)),
                ('izoh', models.CharField(blank=True, default='', max_length=500)),
                ('savol', models.JSONField(blank=True, default=dict)),
                ('holat', models.CharField(choices=[('yangi', 'yangi'), ('tuzatildi', 'tuzatildi'), ('rad', 'xato emas')], default='yangi', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('hal_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('pupil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xato_xabarlari', to='core.pupil')),
            ],
            options={
                'db_table': 'xato_xabar',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['holat', 'created_at'], name='xato_xabar_holat_f90698_idx'), models.Index(fields=['kalit'], name='xato_xabar_kalit_ff58ce_idx')],
            },
        ),
    ]
