# Generated by Django 6.0.6 on 2026-10-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_xato_xabar_kun_savoli'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupil',
            name='songgi_kurs',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
