# Generated by Django 6.0.6 on 2026-10-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_pupil_songgi_kurs'),
    ]

    operations = [
        migrations.AddField(
            model_name='duel',
            name='eslatma_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='duel',
            name='xabar_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='dueltaklif',
            name='korildi_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
