/**
 * TO'LIQ DARSLAR — oliy matematika (1- va 2-kurs) hamda ehtimollar nazariyasi.
 *
 * Ilgari bu uch kursda nazariya UMUMAN yo'q edi: talaba "x bo'yicha xususiy
 * hosila" darsini ochardi va birinchi ekrandayoq savolga duch kelardi —
 * tushuncha ham, namuna ham yo'q. Endi har dars avval g'oyani, formulani,
 * yechish tartibini va qo'lda yechilgan misolni ko'rsatadi
 * (`components/Kirish.tsx`), savollar undan keyin.
 *
 * Kalit "kursId|dars nomi": oliy kurs darslari maktab kurslaridagi
 * nomdoshlari bilan aralashmasin (`nazariya.ts` → `tolaq`).
 * Misollardagi hamma son qo'lda tekshirilgan.
 */
import type { Tolaq } from "./nazariya";

export const TOLAQ_OLIY: Record<string, Tolaq> = {
  /* ═══════════════════════ 1-kurs · chiziqli algebra ═══════════════════════ */
  "oliy1|2×2 determinant": {
    t: [{ h: ["Determinant nima", "Что такое определитель"],
      p: ["Determinant — kvadrat jadvalga (matritsaga) mos qo'yiladigan bitta son. 2×2 jadvalda u bosh diagonal ko'paytmasidan yon diagonal ko'paytmasini ayirish bilan topiladi. Determinant nolga teng bo'lmasa, sistema yagona yechimga ega.",
        "Определитель — число, которое ставится в соответствие квадратной таблице (матрице). Для таблицы 2×2 это произведение главной диагонали минус произведение побочной. Если определитель не равен нулю, система имеет единственное решение."] }],
    f: [{ n: ["2×2 determinant", "Определитель 2×2"], f: "det [ a  b ; c  d ] = a·d − b·c" }],
    s: [
      ["Bosh diagonalni ko'paytiring: a · d.", "Перемножьте главную диагональ: a · d."],
      ["Yon diagonalni ko'paytiring: b · c.", "Перемножьте побочную диагональ: b · c."],
      ["Birinchisidan ikkinchisini ayiring — ishoralarga e'tibor bering.", "Вычтите второе из первого — следите за знаками."],
    ],
    m: [{ s: ["det [ 3  −2 ; 4  5 ] ni hisoblang.", "Вычислите det [ 3  −2 ; 4  5 ]."],
      y: ["a·d = 3 · 5 = 15", "b·c = (−2) · 4 = −8", "15 − (−8) = 15 + 8"], j: "23" }],
    x: [["Minusni yo'qotish: 15 − (−8) bu 7 emas, 23.", "Потерять минус: 15 − (−8) — это не 7, а 23."]],
  },
  "oliy1|3×3 determinant": {
    t: [{ h: ["Birinchi satr bo'yicha yoyish", "Разложение по первой строке"],
      p: ["3×3 determinant uchta 2×2 determinantga keltiriladi. Birinchi satrning har bir elementi o'z satri va ustuni o'chirilganda qolgan 2×2 determinantga ko'paytiriladi; ishoralar navbat bilan: +, −, +.",
        "Определитель 3×3 сводится к трём определителям 2×2. Каждый элемент первой строки умножается на определитель 2×2, который остаётся после вычёркивания его строки и столбца; знаки чередуются: +, −, +."] }],
    f: [{ n: ["Yoyish", "Разложение"], f: "det A = a₁₁·M₁₁ − a₁₂·M₁₂ + a₁₃·M₁₃" }],
    s: [
      ["Birinchi satr elementini oling, uning satri va ustunini o'chiring.", "Возьмите элемент первой строки, вычеркните его строку и столбец."],
      ["Qolgan 2×2 determinantni hisoblang (ad − bc).", "Вычислите оставшийся определитель 2×2 (ad − bc)."],
      ["Uchala ko'paytmani + − + ishoralari bilan qo'shing.", "Сложите три произведения со знаками + − +."],
    ],
    m: [{ s: ["det [ 1 2 0 ; 3 1 2 ; 0 1 1 ] ni hisoblang.", "Вычислите det [ 1 2 0 ; 3 1 2 ; 0 1 1 ]."],
      y: ["1 · (1·1 − 2·1) = 1 · (−1) = −1", "−2 · (3·1 − 2·0) = −2 · 3 = −6", "+0 · (…) = 0", "−1 − 6 + 0"], j: "−7" }],
    x: [["O'rtadagi had oldidagi minusni unutish.", "Забыть минус перед средним слагаемым."],
      ["Satrda nol bo'lsa — o'sha had nol, uni hisoblamang.", "Если в строке есть ноль — это слагаемое равно нулю, не считайте его."]],
  },
  "oliy1|Matritsalar ustida amallar": {
    t: [{ h: ["Element-element", "Поэлементно"],
      p: ["Bir xil o'lchamli matritsalar mos elementlari bo'yicha qo'shiladi va ayiriladi. Songa ko'paytirganda HAR BIR element shu songa ko'paytiriladi. cᵢⱼ — i-satr va j-ustundagi element.",
        "Матрицы одного размера складываются и вычитаются по соответствующим элементам. При умножении на число КАЖДЫЙ элемент умножается на это число. cᵢⱼ — элемент i-й строки и j-го столбца."] }],
    f: [{ n: ["Qo'shish", "Сложение"], f: "(A + B)ᵢⱼ = aᵢⱼ + bᵢⱼ" },
      { n: ["Songa ko'paytirish", "Умножение на число"], f: "(kA)ᵢⱼ = k · aᵢⱼ" }],
    s: [
      ["So'ralgan o'rinni aniqlang: birinchi indeks — satr, ikkinchisi — ustun.", "Определите нужное место: первый индекс — строка, второй — столбец."],
      ["A va B dan aynan shu o'rindagi elementlarni oling.", "Возьмите элементы именно на этом месте из A и B."],
      ["Ifodani faqat shu ikki son bilan hisoblang.", "Вычислите выражение только с этими двумя числами."],
    ],
    m: [{ s: ["A = [ 2  1 ; 0  3 ],  B = [ 1  4 ; 2  −1 ],  C = 2A − B.  c₁₂ = ?", "A = [ 2  1 ; 0  3 ],  B = [ 1  4 ; 2  −1 ],  C = 2A − B.  c₁₂ = ?"],
      y: ["a₁₂ = 1,   b₁₂ = 4", "c₁₂ = 2 · 1 − 4"], j: "−2" }],
    x: [["Satr va ustunni almashtirib yuborish: c₁₂ — 1-satr, 2-ustun.", "Перепутать строку и столбец: c₁₂ — 1-я строка, 2-й столбец."]],
  },
  "oliy1|Matritsalarni ko'paytirish": {
    t: [{ h: ["Satr ustunga", "Строка на столбец"],
      p: ["Ko'paytma element-element EMAS. cᵢⱼ ni topish uchun A ning i-satri B ning j-ustuniga \"skalyar\" ko'paytiriladi: mos elementlar ko'paytirilib, natijalar qo'shiladi. Umuman olganda A·B ≠ B·A.",
        "Произведение НЕ поэлементное. Чтобы найти cᵢⱼ, i-я строка A «скалярно» умножается на j-й столбец B: соответствующие элементы перемножаются и складываются. В общем случае A·B ≠ B·A."] }],
    f: [{ n: ["2×2 uchun", "Для 2×2"], f: "cᵢⱼ = aᵢ₁·b₁ⱼ + aᵢ₂·b₂ⱼ" }],
    s: [
      ["A dan i-satrni, B dan j-ustunni ajrating.", "Выделите i-ю строку A и j-й столбец B."],
      ["Birinchi elementlarni, keyin ikkinchi elementlarni ko'paytiring.", "Перемножьте первые элементы, затем вторые."],
      ["Ikki ko'paytmani qo'shing.", "Сложите два произведения."],
    ],
    m: [{ s: ["A = [ 1  2 ; 3  0 ],  B = [ 4  1 ; −1  2 ],  C = A·B.  c₁₁ = ?", "A = [ 1  2 ; 3  0 ],  B = [ 4  1 ; −1  2 ],  C = A·B.  c₁₁ = ?"],
      y: ["1-satr: (1; 2),   1-ustun: (4; −1)", "1·4 + 2·(−1) = 4 − 2"], j: "2" }],
    x: [["Element-element ko'paytirish (1·4 = 4 deb to'xtash).", "Умножать поэлементно (остановиться на 1·4 = 4)."]],
  },
  "oliy1|Kramer usuli": {
    t: [{ h: ["Sistemani determinant bilan", "Система через определители"],
      p: ["Ikki noma'lumli sistemada Δ — koeffitsiyentlar determinanti. Δₓ ni topish uchun x ustuni o'rniga ozod hadlar ustuni qo'yiladi. Δ ≠ 0 bo'lsa, yechim yagona.",
        "В системе с двумя неизвестными Δ — определитель коэффициентов. Чтобы получить Δₓ, столбец x заменяют столбцом свободных членов. Если Δ ≠ 0, решение единственно."] }],
    f: [{ n: ["Kramer formulalari", "Формулы Крамера"], f: "x = Δₓ / Δ,   y = Δᵧ / Δ" },
      { n: ["Sistema", "Система"], f: "{ a₁x + b₁y = c₁ ;  a₂x + b₂y = c₂ }" }],
    s: [
      ["Δ = a₁b₂ − b₁a₂ ni hisoblang.", "Вычислите Δ = a₁b₂ − b₁a₂."],
      ["x ustunini (c₁; c₂) bilan almashtiring: Δₓ = c₁b₂ − b₁c₂.", "Замените столбец x на (c₁; c₂): Δₓ = c₁b₂ − b₁c₂."],
      ["x = Δₓ / Δ.", "x = Δₓ / Δ."],
    ],
    m: [{ s: ["{ 2x + y = 5 ;  x − y = 1 } — x ni toping.", "{ 2x + y = 5 ;  x − y = 1 } — найдите x."],
      y: ["Δ = 2·(−1) − 1·1 = −3", "Δₓ = 5·(−1) − 1·1 = −6", "x = −6 / (−3)"], j: "2" }],
    x: [["Δₓ da noto'g'ri ustunni almashtirish: x uchun BIRINCHI ustun almashadi.", "В Δₓ заменить не тот столбец: для x меняется ПЕРВЫЙ столбец."]],
  },

  /* ═══════════════════════ 1-kurs · vektorlar ═══════════════════════ */
  "oliy1|Vektor uzunligi": {
    t: [{ h: ["Fazodagi Pifagor", "Пифагор в пространстве"],
      p: ["Vektor uzunligi — boshidan oxirigacha bo'lgan masofa. Fazoda u uch koordinata kvadratlari yig'indisining ildizi: tekislikdagi Pifagor teoremasiga uchinchi o'lcham qo'shilgan.",
        "Длина вектора — расстояние от начала до конца. В пространстве это корень из суммы квадратов трёх координат: теорема Пифагора с третьим измерением."] }],
    f: [{ n: ["Uzunlik", "Длина"], f: "|a| = √(x² + y² + z²)" }],
    s: [
      ["Har koordinatani kvadratga ko'taring — manfiy son ham musbat bo'ladi.", "Возведите каждую координату в квадрат — отрицательное станет положительным."],
      ["Kvadratlarni qo'shing.", "Сложите квадраты."],
      ["Ildiz chiqaring.", "Извлеките корень."],
    ],
    m: [{ s: ["a = (2; −3; 6).  |a| = ?", "a = (2; −3; 6).  |a| = ?"], y: ["4 + 9 + 36 = 49", "√49"], j: "7" }],
    x: [["(−3)² ni −9 deb yozish. Kvadrat doim musbat.", "Записать (−3)² как −9. Квадрат всегда положителен."]],
  },
  "oliy1|Skalyar ko'paytma": {
    t: [{ h: ["Natija — son", "Результат — число"],
      p: ["Skalyar ko'paytma ikki vektordan bitta SON hosil qiladi: mos koordinatalar ko'paytirilib qo'shiladi. U vektorlar orasidagi burchakni ham beradi: ko'paytma nol bo'lsa, vektorlar perpendikulyar.",
        "Скалярное произведение из двух векторов даёт одно ЧИСЛО: соответствующие координаты перемножаются и складываются. Оно связано с углом между векторами: если произведение равно нулю, векторы перпендикулярны."] }],
    f: [{ n: ["Koordinatalar orqali", "Через координаты"], f: "a·b = x₁x₂ + y₁y₂ + z₁z₂" },
      { n: ["Burchak orqali", "Через угол"], f: "a·b = |a| · |b| · cos φ" }],
    s: [
      ["Mos koordinatalarni juftlab ko'paytiring.", "Перемножьте соответствующие координаты попарно."],
      ["Uch ko'paytmani ishoralari bilan qo'shing.", "Сложите три произведения с учётом знаков."],
    ],
    m: [{ s: ["a = (1; −2; 3),  b = (4; 0; −1).  a·b = ?", "a = (1; −2; 3),  b = (4; 0; −1).  a·b = ?"],
      y: ["1·4 = 4,   (−2)·0 = 0,   3·(−1) = −3", "4 + 0 − 3"], j: "1" }],
    x: [["Javobni vektor qilib yozish. Skalyar ko'paytma — bitta son.", "Записать ответ вектором. Скалярное произведение — одно число."]],
  },
  "oliy1|Perpendikulyarlik sharti": {
    t: [{ h: ["To'g'ri burchak — nol ko'paytma", "Прямой угол — нулевое произведение"],
      p: ["cos 90° = 0, shuning uchun perpendikulyar vektorlarning skalyar ko'paytmasi nolga teng. Noma'lum koordinata shu shartdan tenglama bo'lib chiqadi.",
        "cos 90° = 0, поэтому скалярное произведение перпендикулярных векторов равно нулю. Неизвестная координата находится из этого условия как из уравнения."] }],
    f: [{ n: ["Shart", "Условие"], f: "a ⊥ b   ⇔   x₁x₂ + y₁y₂ + z₁z₂ = 0" }],
    s: [
      ["Skalyar ko'paytmani k bilan yozing.", "Запишите скалярное произведение с k."],
      ["Uni nolga tenglang.", "Приравняйте его к нулю."],
      ["Chiziqli tenglamadan k ni toping.", "Найдите k из линейного уравнения."],
    ],
    m: [{ s: ["a = (2; −1; 3),  b = (k; 4; 2),  a ⊥ b.  k = ?", "a = (2; −1; 3),  b = (k; 4; 2),  a ⊥ b.  k = ?"],
      y: ["2k + (−1)·4 + 3·2 = 0", "2k − 4 + 6 = 0  →  2k = −2"], j: "−1" }],
    x: [["Sonlarni o'ng tomonga o'tkazganda ishorani almashtirmaslik.", "Не сменить знак при переносе чисел вправо."]],
  },
  "oliy1|Vektor ko'paytma": {
    t: [{ h: ["Natija — vektor", "Результат — вектор"],
      p: ["Vektor ko'paytma a × b ikkala vektorga perpendikulyar yangi VEKTOR beradi; uning uzunligi shu vektorlarga qurilgan parallelogramm yuziga teng. Har koordinata 2×2 determinant bilan topiladi.",
        "Векторное произведение a × b даёт новый ВЕКТОР, перпендикулярный обоим; его длина равна площади параллелограмма на этих векторах. Каждая координата находится определителем 2×2."] }],
    f: [{ n: ["Koordinatalar", "Координаты"], f: "a × b = (y₁z₂ − z₁y₂;  z₁x₂ − x₁z₂;  x₁y₂ − y₁x₂)" }],
    s: [
      ["z-koordinata uchun faqat x va y lar kerak.", "Для z-координаты нужны только x и y."],
      ["x₁y₂ ni hisoblang, keyin y₁x₂ ni.", "Вычислите x₁y₂, затем y₁x₂."],
      ["Birinchisidan ikkinchisini ayiring.", "Вычтите второе из первого."],
    ],
    m: [{ s: ["a = (1; 2; 3),  b = (4; −1; 2).  (a × b)_z = ?", "a = (1; 2; 3),  b = (4; −1; 2).  (a × b)_z = ?"],
      y: ["x₁y₂ = 1·(−1) = −1", "y₁x₂ = 2·4 = 8", "−1 − 8"], j: "−9" }],
    x: [["Tartibni almashtirish: a × b = −(b × a), ishora teskari bo'ladi.", "Перепутать порядок: a × b = −(b × a), знак меняется."]],
  },

  /* ═══════════════════════ 1-kurs · limitlar ═══════════════════════ */
  "oliy1|Cheksizlikdagi limit": {
    t: [{ h: ["Faqat bosh hadlar", "Только старшие члены"],
      p: ["x juda katta bo'lganda eng yuqori darajali had qolganlarini \"yutib yuboradi\". Surat va maxraj darajasi teng bo'lsa, limit bosh koeffitsiyentlar nisbatiga teng.",
        "При очень больших x старший член «поглощает» остальные. Если степени числителя и знаменателя равны, предел равен отношению старших коэффициентов."] }],
    f: [{ n: ["Darajalar teng", "Степени равны"], f: "lim (axⁿ + …) / (bxⁿ + …) = a / b" },
      { n: ["Surat darajasi kichik", "Степень числителя меньше"], f: "lim = 0" }],
    s: [
      ["Surat va maxrajning eng yuqori darajasini toping.", "Найдите старшие степени числителя и знаменателя."],
      ["Darajalar teng bo'lsa — bosh koeffitsiyentlarni bo'ling.", "Если степени равны — разделите старшие коэффициенты."],
      ["Kasrni qisqartiring.", "Сократите дробь."],
    ],
    m: [{ s: ["lim (4x² − x + 1) / (2x² + 3),  x → ∞", "lim (4x² − x + 1) / (2x² + 3),  x → ∞"],
      y: ["Ikkalasida ham x²", "4 / 2"], j: "2" }],
    x: [["Kichik hadlarni (−x, +1, +3) ham hisobga olish — ular cheksizlikda ta'sir qilmaydi.", "Учитывать младшие члены (−x, +1, +3) — на бесконечности они не влияют."]],
  },
  "oliy1|0/0 noaniqlik": {
    t: [{ h: ["Qisqartirish", "Сокращение"],
      p: ["Nuqtani qo'yganda 0/0 chiqsa, surat va maxrajda bir xil ko'paytuvchi (x − a) bor. Suratni ko'paytuvchilarga ajratib, uni qisqartiramiz va shundan keyingina nuqtani qo'yamiz.",
        "Если при подстановке получается 0/0, в числителе и знаменателе есть общий множитель (x − a). Раскладываем числитель, сокращаем и только потом подставляем точку."] }],
    f: [{ n: ["Ajratish", "Разложение"], f: "x² + px + q = (x − x₁)(x − x₂)" }],
    s: [
      ["Nuqtani qo'yib, 0/0 ekanini tekshiring.", "Подставьте точку и убедитесь, что получается 0/0."],
      ["Suratni ko'paytuvchilarga ajrating.", "Разложите числитель на множители."],
      ["(x − a) ni qisqartiring va nuqtani qo'ying.", "Сократите (x − a) и подставьте точку."],
    ],
    m: [{ s: ["lim (x² − 5x + 6) / (x − 2),  x → 2", "lim (x² − 5x + 6) / (x − 2),  x → 2"],
      y: ["x² − 5x + 6 = (x − 2)(x − 3)", "Qisqargach: x − 3", "2 − 3"], j: "−1" }],
    x: [["0/0 ni \"nol\" yoki \"mavjud emas\" deb javob berish.", "Отвечать на 0/0 «ноль» или «не существует»."]],
  },
  "oliy1|Birinchi ajoyib limit": {
    t: [{ h: ["sin x ≈ x", "sin x ≈ x"],
      p: ["Nolga yaqin joyda sin x deyarli x ga teng, tg x ham. Shuning uchun sin(ax), tg(ax) o'rniga ax qo'yish mumkin — limit koeffitsiyentlar nisbatiga aylanadi.",
        "Вблизи нуля sin x почти равен x, и tg x тоже. Поэтому sin(ax), tg(ax) можно заменить на ax — предел превращается в отношение коэффициентов."] }],
    f: [{ n: ["Ajoyib limit", "Замечательный предел"], f: "lim sin x / x = 1,   x → 0" },
      { n: ["Natija", "Следствие"], f: "lim sin(ax) / sin(bx) = a / b" }],
    s: [
      ["sin(ax) va tg(ax) ni ax bilan almashtiring.", "Замените sin(ax) и tg(ax) на ax."],
      ["x ni qisqartiring.", "Сократите x."],
      ["Koeffitsiyentlar nisbatini soddalashtiring.", "Упростите отношение коэффициентов."],
    ],
    m: [{ s: ["lim sin(3x) / tg(6x),  x → 0", "lim sin(3x) / tg(6x),  x → 0"], y: ["≈ 3x / 6x", "3 / 6"], j: "1/2" }],
    x: [["Bu almashtirish faqat x → 0 da ishlaydi, x → ∞ da emas.", "Эта замена работает только при x → 0, не при x → ∞."]],
  },

  /* ═══════════════════════ 1-kurs · hosila ═══════════════════════ */
  "oliy1|Ko'paytmaning hosilasi": {
    t: [{ h: ["Navbat bilan", "По очереди"],
      p: ["Ko'paytmaning hosilasi hosilalar ko'paytmasi EMAS. Avval birinchi ko'paytuvchi differensiallanadi (ikkinchisi o'zgarmay turadi), keyin ikkinchisi — va natijalar qo'shiladi.",
        "Производная произведения — НЕ произведение производных. Сначала дифференцируется первый множитель (второй остаётся), затем второй — и результаты складываются."] }],
    f: [{ n: ["Leybnits qoidasi", "Правило Лейбница"], f: "(u · v)′ = u′v + uv′" }],
    s: [
      ["u va v ni ajrating, u′ va v′ ni toping.", "Выделите u и v, найдите u′ и v′."],
      ["u′v + uv′ ni tuzing.", "Составьте u′v + uv′."],
      ["Nuqtani qo'yib hisoblang.", "Подставьте точку и вычислите."],
    ],
    m: [{ s: ["y = (2x)(x² + 1).  y′(1) = ?", "y = (2x)(x² + 1).  y′(1) = ?"],
      y: ["u = 2x, u′ = 2;   v = x² + 1, v′ = 2x", "y′ = 2(x² + 1) + 2x · 2x", "y′(1) = 2·2 + 4"], j: "8" }],
    x: [["(uv)′ = u′ · v′ deb yozish — eng ko'p uchraydigan xato.", "Писать (uv)′ = u′ · v′ — самая частая ошибка."]],
  },
  "oliy1|Murakkab funksiya hosilasi": {
    t: [{ h: ["Zanjir qoidasi", "Цепное правило"],
      p: ["Funksiya ichida funksiya bo'lsa (masalan (3x + 5)³), avval tashqi funksiya hosilasi olinadi — ichkisi o'zgarmay turadi — keyin ichki funksiya hosilasiga ko'paytiriladi.",
        "Если внутри функции стоит другая функция (например (3x + 5)³), сначала берётся производная внешней — внутренняя остаётся — затем умножается на производную внутренней."] }],
    f: [{ n: ["Zanjir qoidasi", "Цепное правило"], f: "(f(g(x)))′ = f′(g) · g′(x)" },
      { n: ["Daraja uchun", "Для степени"], f: "((ax + b)ⁿ)′ = n(ax + b)ⁿ⁻¹ · a" }],
    s: [
      ["Tashqi va ichki funksiyani ajrating.", "Выделите внешнюю и внутреннюю функции."],
      ["Tashqisini differensiallang, ichkisini o'zgartirmang.", "Продифференцируйте внешнюю, не меняя внутреннюю."],
      ["Ichki funksiya hosilasiga ko'paytiring va nuqtani qo'ying.", "Умножьте на производную внутренней и подставьте точку."],
    ],
    m: [{ s: ["y = (2x + 1)³.  y′(1) = ?", "y = (2x + 1)³.  y′(1) = ?"],
      y: ["y′ = 3(2x + 1)² · 2 = 6(2x + 1)²", "y′(1) = 6 · 3² = 6 · 9"], j: "54" }],
    x: [["Ichki funksiya hosilasiga (bu yerda 2 ga) ko'paytirishni unutish.", "Забыть умножить на производную внутренней функции (здесь на 2)."]],
  },
  "oliy1|Ko'rsatkichli funksiya hosilasi": {
    t: [{ h: ["eˣ — o'z hosilasi", "eˣ — своя производная"],
      p: ["eˣ funksiyaning hosilasi o'ziga teng. Ko'rsatkichda kx tursa, zanjir qoidasi bo'yicha oldinga k chiqadi; oldidagi son ko'paytuvchi bo'lib qoladi.",
        "Производная eˣ равна самой функции. Если в показателе стоит kx, по цепному правилу вперёд выходит k; числовой множитель сохраняется."] }],
    f: [{ n: ["Asosiy", "Основная"], f: "(eˣ)′ = eˣ" }, { n: ["Ko'rsatkichda kx", "В показателе kx"], f: "(a · e^(kx))′ = a·k · e^(kx)" }],
    s: [
      ["Ko'rsatkichdagi koeffitsiyent k ni aniqlang.", "Определите коэффициент k в показателе."],
      ["Oldidagi sonni k ga ko'paytiring.", "Умножьте числовой множитель на k."],
      ["e^(kx) ni o'zgarishsiz yozing.", "Запишите e^(kx) без изменений."],
    ],
    m: [{ s: ["y = 3e^(−2x).  y′ = ?", "y = 3e^(−2x).  y′ = ?"], y: ["k = −2", "3 · (−2) = −6"], j: "−6e^(−2x)" }],
    x: [["Ko'rsatkichni o'zgartirish (e^(−2x) → e^(−2x−1)): bu daraja funksiyasi qoidasi, ko'rsatkichliniki emas.", "Менять показатель (e^(−2x) → e^(−2x−1)): это правило степенной функции, а не показательной."]],
  },

  /* ═══════════════════════ 1-kurs · integral ═══════════════════════ */
  "oliy1|Nyuton–Leybnits formulasi": {
    t: [{ h: ["Boshlang'ich funksiya ayirmasi", "Разность первообразных"],
      p: ["Aniq integral — egri chiziq ostidagi (ishorali) yuza. Uni topish uchun boshlang'ich funksiya F(x) olinadi va yuqori chegaradagi qiymatidan quyi chegaradagisi ayiriladi.",
        "Определённый интеграл — (знаковая) площадь под кривой. Чтобы его найти, берут первообразную F(x) и вычитают её значение на нижнем пределе из значения на верхнем."] }],
    f: [{ n: ["Formula", "Формула"], f: "∫ₐᵇ f(x) dx = F(b) − F(a)" }, { n: ["Daraja", "Степень"], f: "∫ xⁿ dx = xⁿ⁺¹ / (n + 1)" }],
    s: [
      ["Har had uchun boshlang'ich funksiyani toping.", "Найдите первообразную для каждого слагаемого."],
      ["Yuqori chegarani qo'ying: F(b).", "Подставьте верхний предел: F(b)."],
      ["Quyi chegarani qo'ying va ayiring: F(b) − F(a).", "Подставьте нижний и вычтите: F(b) − F(a)."],
    ],
    m: [{ s: ["∫ (2x + 3) dx,  0 → 2", "∫ (2x + 3) dx,  0 → 2"], y: ["F(x) = x² + 3x", "F(2) = 4 + 6 = 10,   F(0) = 0", "10 − 0"], j: "10" }],
    x: [["F(a) − F(b) deb teskari ayirish.", "Вычитать наоборот: F(a) − F(b)."]],
  },
  "oliy1|Bo'laklab integrallash": {
    t: [{ h: ["Ko'paytmani integrallash", "Интегрирование произведения"],
      p: ["x·sin x, x·eˣ kabi ko'paytmalar to'g'ridan-to'g'ri integrallanmaydi. u deb hosilasi soddalashadigan qism (odatda x) olinadi, qolgani dv bo'ladi — integral soddaroq integralga almashadi.",
        "Произведения вида x·sin x, x·eˣ напрямую не интегрируются. За u берут часть, которая упрощается при дифференцировании (обычно x), остальное — dv; интеграл заменяется более простым."] }],
    f: [{ n: ["Formula", "Формула"], f: "∫ u dv = uv − ∫ v du" }],
    s: [
      ["u = x deb oling, du = dx.", "Возьмите u = x, du = dx."],
      ["dv dan v ni toping (integrallab).", "Найдите v из dv (интегрированием)."],
      ["uv − ∫ v du ni yozing va chegaralarni qo'ying.", "Запишите uv − ∫ v du и подставьте пределы."],
    ],
    m: [{ s: ["∫ x·cos x dx,  0 → π/2", "∫ x·cos x dx,  0 → π/2"],
      y: ["u = x,  dv = cos x dx  →  v = sin x", "x·sin x − ∫ sin x dx = x·sin x + cos x", "(π/2 · 1 + 0) − (0 + 1)"], j: "π/2 − 1" }],
    x: [["u ni noto'g'ri tanlash: u = sin x olinsa, integral murakkablashadi.", "Неудачный выбор u: при u = sin x интеграл усложняется."]],
  },

  /* ═══════════════════════ 1-kurs · qatorlar va DT ═══════════════════════ */
  "oliy1|Geometrik qator yig'indisi": {
    t: [{ h: ["Cheksiz, lekin chekli", "Бесконечно, но конечно"],
      p: ["Har hadi oldingisidan q marta kichik bo'lgan cheksiz yig'indi |q| < 1 bo'lganda chekli songa yaqinlashadi. |q| ≥ 1 bo'lsa, yig'indi mavjud emas.",
        "Бесконечная сумма, где каждый член в q раз меньше предыдущего, сходится к конечному числу при |q| < 1. При |q| ≥ 1 суммы не существует."] }],
    f: [{ n: ["Yig'indi", "Сумма"], f: "Σ a·qⁿ = a / (1 − q),   |q| < 1" }],
    s: [
      ["Birinchi had a va maxraj q ni aniqlang.", "Определите первый член a и знаменатель q."],
      ["|q| < 1 ekanini tekshiring.", "Проверьте, что |q| < 1."],
      ["a / (1 − q) ni hisoblang.", "Вычислите a / (1 − q)."],
    ],
    m: [{ s: ["Σ 2·(1/3)ⁿ,  n = 0 … ∞", "Σ 2·(1/3)ⁿ,  n = 0 … ∞"], y: ["a = 2,  q = 1/3", "2 / (1 − 1/3) = 2 / (2/3)"], j: "3" }],
    x: [["1 − q o'rniga 1 + q yozish yoki kasrga bo'lishda adashish.", "Писать 1 + q вместо 1 − q или ошибаться при делении на дробь."]],
  },
  "oliy1|y′ = ky tenglamasi": {
    t: [{ h: ["O'sish tezligi miqdorga proporsional", "Скорость роста пропорциональна величине"],
      p: ["y′ = ky — \"qancha ko'p bo'lsa, shuncha tez o'sadi\" qonuni: bakteriya, foiz, radioaktiv yemirilish. Uning yechimi doim ko'rsatkichli funksiya; C boshlang'ich shartdan topiladi.",
        "y′ = ky — закон «чем больше, тем быстрее растёт»: бактерии, проценты, радиоактивный распад. Решение всегда показательная функция; C находится из начального условия."] }],
    f: [{ n: ["Umumiy yechim", "Общее решение"], f: "y′ = ky   ⇒   y = C·e^(kx)" }, { n: ["Boshlang'ich shart", "Начальное условие"], f: "y(0) = C" }],
    s: [
      ["k ni tenglamadan o'qing.", "Считайте k из уравнения."],
      ["y = C·e^(kx) deb yozing.", "Запишите y = C·e^(kx)."],
      ["x = 0 da e⁰ = 1, demak C = y(0).", "При x = 0 e⁰ = 1, значит C = y(0)."],
    ],
    m: [{ s: ["y′ = 2y,  y(0) = 5", "y′ = 2y,  y(0) = 5"], y: ["k = 2  →  y = C·e^(2x)", "y(0) = C = 5"], j: "y = 5e^(2x)" }],
    x: [["C ni ko'rsatkichga qo'shib yuborish: y = e^(2x + 5) noto'g'ri.", "Отправить C в показатель: y = e^(2x + 5) неверно."]],
  },

  /* ═══════════════════════ 2-kurs · ko'p o'zgaruvchili ═══════════════════════ */
  "oliy2|x bo'yicha xususiy hosila": {
    t: [{ h: ["Bittasi o'zgaradi, qolgani — son", "Одна меняется, остальные — числа"],
      p: ["f(x, y) ikki o'zgaruvchiga bog'liq. ∂f/∂x — faqat x o'zgarganda funksiya qanchalik tez o'zgarishini ko'rsatadi. Hisoblashda y ni oddiy SON deb qaraymiz va x bo'yicha odatdagi hosila qoidalarini qo'llaymiz.",
        "f(x, y) зависит от двух переменных. ∂f/∂x показывает, как быстро меняется функция, когда меняется только x. При вычислении считаем y обычным ЧИСЛОМ и применяем обычные правила производной по x."] },
    { h: ["Nuqtadagi qiymat", "Значение в точке"],
      p: ["Avval umumiy ko'rinishda hosila olinadi, shundan keyingina nuqta koordinatalari qo'yiladi — avval qo'yilsa, funksiya songa aylanib, hosilasi nol bo'lib qoladi.",
        "Сначала находят производную в общем виде и только потом подставляют координаты точки — если подставить раньше, функция превратится в число, и производная будет нулём."] }],
    f: [{ n: ["Daraja", "Степень"], f: "∂(xⁿ)/∂x = n·xⁿ⁻¹" },
      { n: ["y — ko'paytuvchi", "y — множитель"], f: "∂(x²y)/∂x = 2xy,   ∂(xy³)/∂x = y³" },
      { n: ["Faqat y bor had", "Слагаемое только с y"], f: "∂(y²)/∂x = 0" }],
    s: [
      ["Har hadda y ni son deb belgilang.", "В каждом слагаемом считайте y числом."],
      ["x bo'yicha hosila oling: daraja oldinga tushadi, bittaga kamayadi.", "Возьмите производную по x: показатель выходит вперёд и уменьшается на 1."],
      ["x siz hadlarni tashlang — ularning hosilasi nol.", "Отбросьте слагаемые без x — их производная равна нулю."],
      ["Nuqta koordinatalarini qo'yib hisoblang.", "Подставьте координаты точки и вычислите."],
    ],
    m: [{ s: ["f = 2x²y + xy³ − 3x.  ∂f/∂x (−1; −1) = ?", "f = 2x²y + xy³ − 3x.  ∂f/∂x (−1; −1) = ?"],
      y: ["∂(2x²y)/∂x = 4xy", "∂(xy³)/∂x = y³,   ∂(−3x)/∂x = −3", "∂f/∂x = 4xy + y³ − 3", "4·(−1)·(−1) + (−1)³ − 3 = 4 − 1 − 3"], j: "0" }],
    x: [["y ni ham differensiallash: ∂(x²y)/∂x = 2xy, 2x emas va 2xy′ emas.", "Дифференцировать и y: ∂(x²y)/∂x = 2xy, а не 2x и не 2xy′."],
      ["(−1)³ = −1 ekanini unutish — toq daraja ishorani saqlaydi.", "Забыть, что (−1)³ = −1 — нечётная степень сохраняет знак."]],
  },
  "oliy2|y bo'yicha xususiy hosila": {
    t: [{ h: ["Endi x — son", "Теперь x — число"],
      p: ["∂f/∂y da rollar almashadi: x o'zgarmas son, y esa o'zgaruvchi. Faqat x bor hadlar (masalan 3x²) y ga bog'liq emas — ularning hosilasi nol.",
        "В ∂f/∂y роли меняются: x — постоянное число, y — переменная. Слагаемые только с x (например 3x²) от y не зависят — их производная равна нулю."] }],
    f: [{ n: ["y — o'zgaruvchi", "y — переменная"], f: "∂(xy²)/∂y = 2xy,   ∂(xy³)/∂y = 3xy²" }, { n: ["Faqat x bor had", "Слагаемое только с x"], f: "∂(x²)/∂y = 0" }],
    s: [
      ["x ni son deb belgilang.", "Считайте x числом."],
      ["Har hadni y bo'yicha differensiallang.", "Продифференцируйте каждое слагаемое по y."],
      ["Nuqta koordinatalarini qo'ying.", "Подставьте координаты точки."],
    ],
    m: [{ s: ["f = 3x² − 2xy².  ∂f/∂y (1; −2) = ?", "f = 3x² − 2xy².  ∂f/∂y (1; −2) = ?"],
      y: ["∂(3x²)/∂y = 0", "∂(−2xy²)/∂y = −4xy", "−4 · 1 · (−2)"], j: "8" }],
    x: [["3x² ni ham differensiallab 6x yozish — bu ∂/∂x, ∂/∂y emas.", "Дифференцировать 3x² и писать 6x — это ∂/∂x, а не ∂/∂y."]],
  },
  "oliy2|Gradient": {
    t: [{ h: ["Eng tez o'sish yo'nalishi", "Направление наибыстрейшего роста"],
      p: ["Gradient — xususiy hosilalardan tuzilgan vektor. U funksiya eng tez o'sadigan tomonni ko'rsatadi, uzunligi esa shu o'sish tezligi. Chiziqli funksiyada gradient hamma nuqtada bir xil.",
        "Градиент — вектор из частных производных. Он указывает направление наибыстрейшего роста функции, а его длина — скорость этого роста. У линейной функции градиент одинаков во всех точках."] }],
    f: [{ n: ["Gradient", "Градиент"], f: "grad f = (∂f/∂x;  ∂f/∂y)" }, { n: ["Uzunligi", "Длина"], f: "|grad f| = √((∂f/∂x)² + (∂f/∂y)²)" }],
    s: [
      ["∂f/∂x va ∂f/∂y ni toping.", "Найдите ∂f/∂x и ∂f/∂y."],
      ["Ikkalasini kvadratga ko'tarib qo'shing.", "Возведите оба в квадрат и сложите."],
      ["Ildiz chiqaring.", "Извлеките корень."],
    ],
    m: [{ s: ["f = 3x − 4y.  |grad f| = ?", "f = 3x − 4y.  |grad f| = ?"], y: ["grad f = (3; −4)", "√(9 + 16) = √25"], j: "5" }],
    x: [["Koordinatalarni shunchaki qo'shish (3 + (−4)) — uzunlik Pifagor bo'yicha topiladi.", "Просто сложить координаты (3 + (−4)) — длина находится по Пифагору."]],
  },
  "oliy2|Ikki o'zgaruvchili funksiya ekstremumi": {
    t: [{ h: ["Ikkala hosila ham nol", "Обе производные равны нулю"],
      p: ["Minimum yoki maksimum nuqtasida funksiya hech bir yo'nalishda o'smaydi — ya'ni ikkala xususiy hosila bir vaqtda nolga teng. Bu ikki tenglama nuqtaning x va y koordinatalarini beradi.",
        "В точке минимума или максимума функция не растёт ни в одном направлении — обе частные производные одновременно равны нулю. Эти два уравнения дают координаты x и y точки."] }],
    f: [{ n: ["Zaruriy shart", "Необходимое условие"], f: "∂f/∂x = 0,   ∂f/∂y = 0" }],
    s: [
      ["∂f/∂x ni topib, nolga tenglang — x chiqadi.", "Найдите ∂f/∂x и приравняйте к нулю — получите x."],
      ["∂f/∂y ni topib, nolga tenglang — y chiqadi.", "Найдите ∂f/∂y и приравняйте к нулю — получите y."],
      ["Javobni (x; y) ko'rinishida yozing.", "Запишите ответ в виде (x; y)."],
    ],
    m: [{ s: ["f = x² + y² − 2x + 6y — minimum nuqtasi?", "f = x² + y² − 2x + 6y — точка минимума?"],
      y: ["∂f/∂x = 2x − 2 = 0  →  x = 1", "∂f/∂y = 2y + 6 = 0  →  y = −3"], j: "(1; −3)" }],
    x: [["Ishorada adashish: 2y + 6 = 0 dan y = −3, +3 emas.", "Ошибка в знаке: из 2y + 6 = 0 следует y = −3, а не +3."]],
  },

  /* ═══════════════════════ 2-kurs · karrali integrallar ═══════════════════════ */
  "oliy2|To'g'ri to'rtburchak bo'yicha integral": {
    t: [{ h: ["Ketma-ket ikki integral", "Два интеграла подряд"],
      p: ["Ikki karrali integral — sirt ostidagi hajm. To'g'ri to'rtburchak sohada u ketma-ket hisoblanadi: avval x bo'yicha (y son deb turadi), keyin natija y bo'yicha integrallanadi.",
        "Двойной интеграл — объём под поверхностью. По прямоугольнику он вычисляется повторно: сначала по x (y считается числом), затем результат интегрируется по y."] }],
    f: [{ n: ["Takroriy integral", "Повторный интеграл"], f: "∬ f dx dy = ∫ ( ∫ f dx ) dy" },
      { n: ["Chiziqli funksiya uchun", "Для линейной функции"], f: "∬ (ax + by) dx dy = a·(X²/2)·Y + b·X·(Y²/2)" }],
    s: [
      ["Ichki integralni x bo'yicha hisoblang, y — son.", "Вычислите внутренний интеграл по x, y — число."],
      ["x chegaralarini qo'ying.", "Подставьте пределы по x."],
      ["Natijani y bo'yicha integrallang.", "Проинтегрируйте результат по y."],
    ],
    m: [{ s: ["∬ (x + 2y) dx dy,  0 ≤ x ≤ 2,  0 ≤ y ≤ 1", "∬ (x + 2y) dx dy,  0 ≤ x ≤ 2,  0 ≤ y ≤ 1"],
      y: ["∫₀² (x + 2y) dx = x²/2 + 2xy |₀² = 2 + 4y", "∫₀¹ (2 + 4y) dy = 2y + 2y² |₀¹ = 2 + 2"], j: "4" }],
    x: [["Ichki integralda y ni ham integrallab yuborish.", "Интегрировать и y во внутреннем интеграле."]],
  },
  "oliy2|Ko'paytmaning karrali integrali": {
    t: [{ h: ["Integral ajraladi", "Интеграл разделяется"],
      p: ["Funksiya g(x)·h(y) ko'rinishida va soha to'g'ri to'rtburchak bo'lsa, ikki karrali integral ikkita oddiy integralning ko'paytmasiga teng. Bu hisobni ikki barobar qisqartiradi.",
        "Если функция имеет вид g(x)·h(y), а область — прямоугольник, двойной интеграл равен произведению двух обычных интегралов. Это вдвое сокращает вычисления."] }],
    f: [{ n: ["Ajratish", "Разделение"], f: "∬ g(x)h(y) dx dy = ∫ g(x) dx · ∫ h(y) dy" }, { n: ["xy uchun", "Для xy"], f: "∫₀ᵃ x dx = a²/2" }],
    s: [
      ["x bo'yicha integralni alohida hisoblang.", "Вычислите интеграл по x отдельно."],
      ["y bo'yicha integralni alohida hisoblang.", "Вычислите интеграл по y отдельно."],
      ["Ikki natijani ko'paytiring.", "Перемножьте два результата."],
    ],
    m: [{ s: ["∬ xy dx dy,  0 ≤ x ≤ 2,  0 ≤ y ≤ 3", "∬ xy dx dy,  0 ≤ x ≤ 2,  0 ≤ y ≤ 3"],
      y: ["∫₀² x dx = 4/2 = 2", "∫₀³ y dy = 9/2", "2 · 9/2"], j: "9" }],
    x: [["Natijalarni qo'shish — ular KO'PAYTIRILADI.", "Складывать результаты — их нужно ПЕРЕМНОЖАТЬ."]],
  },
  "oliy2|Soha yuzi": {
    t: [{ h: ["Birni integrallash — yuza", "Интеграл от единицы — площадь"],
      p: ["Funksiya o'rniga 1 qo'yilsa, ikki karrali integral sohaning YUZINI beradi. Yuqori chegara x ga bog'liq bo'lsa (y ≤ kx), avval y bo'yicha integrallanadi — chegara o'rniga kx tushadi.",
        "Если вместо функции стоит 1, двойной интеграл даёт ПЛОЩАДЬ области. Если верхняя граница зависит от x (y ≤ kx), сначала интегрируют по y — вместо предела подставляется kx."] }],
    f: [{ n: ["Yuza", "Площадь"], f: "S = ∬ dx dy = ∫₀ᵃ ( ∫₀^(kx) dy ) dx = ∫₀ᵃ kx dx = k·a²/2" }],
    s: [
      ["Ichki integral: ∫ dy = yuqori chegara − quyi chegara = kx.", "Внутренний интеграл: ∫ dy = верхний предел − нижний = kx."],
      ["kx ni x bo'yicha 0 dan a gacha integrallang.", "Проинтегрируйте kx по x от 0 до a."],
      ["k · a² / 2 ni hisoblang.", "Вычислите k · a² / 2."],
    ],
    m: [{ s: ["S = ∬ dx dy,  0 ≤ x ≤ 4,  0 ≤ y ≤ 3x", "S = ∬ dx dy,  0 ≤ x ≤ 4,  0 ≤ y ≤ 3x"],
      y: ["∫₀^(3x) dy = 3x", "∫₀⁴ 3x dx = 3 · 16/2"], j: "24" }],
    x: [["Sohani to'g'ri to'rtburchak deb a · ka hisoblash — bu uchburchak, yuzi ikki barobar kichik.", "Считать область прямоугольником a · ka — это треугольник, площадь вдвое меньше."]],
  },

  /* ═══════════════════════ 2-kurs · qatorlar ═══════════════════════ */
  "oliy2|Sonli qatorlarning yaqinlashishi": {
    t: [{ h: ["Hadlar qanchalik tez kichrayadi", "Насколько быстро убывают члены"],
      p: ["Cheksiz yig'indi chekli bo'lishi uchun hadlar nolga intilishi shart, lekin bu yetarli emas: Σ 1/n uzoqlashadi. Σ 1/nᵖ qatori faqat p > 1 da yaqinlashadi. Hadi nolga intilmaydigan qator doim uzoqlashadi.",
        "Чтобы бесконечная сумма была конечной, члены должны стремиться к нулю, но этого мало: Σ 1/n расходится. Ряд Σ 1/nᵖ сходится только при p > 1. Ряд, члены которого не стремятся к нулю, всегда расходится."] }],
    f: [{ n: ["Umumlashgan garmonik qator", "Обобщённый гармонический ряд"], f: "Σ 1/nᵖ:   p > 1 — yaqinlashadi,   p ≤ 1 — uzoqlashadi" },
      { n: ["Zaruriy shart", "Необходимое условие"], f: "aₙ → 0" }],
    s: [
      ["Hadning umumiy ko'rinishini aniqlang.", "Определите общий вид члена ряда."],
      ["Had nolga intiladimi? Yo'q bo'lsa — uzoqlashadi.", "Стремится ли член к нулю? Если нет — расходится."],
      ["1/nᵖ ko'rinishida bo'lsa, p ni 1 bilan solishtiring.", "Если вид 1/nᵖ, сравните p с 1."],
    ],
    m: [{ s: ["Qaysi biri yaqinlashadi: Σ 1/n,  Σ 1/n²,  Σ 1/√n,  Σ n ?", "Какой сходится: Σ 1/n,  Σ 1/n²,  Σ 1/√n,  Σ n ?"],
      y: ["Σ 1/n: p = 1 — uzoqlashadi", "Σ 1/√n: p = 1/2 — uzoqlashadi;   Σ n: had nolga intilmaydi", "Σ 1/n²: p = 2 > 1"], j: "Σ 1/n²" }],
    x: [["\"Hadlar nolga intiladi, demak yaqinlashadi\" deb xulosa qilish — Σ 1/n buning aksi.", "Делать вывод «члены стремятся к нулю — значит сходится»: Σ 1/n — контрпример."]],
  },
  "oliy2|Yaqinlashish radiusi": {
    t: [{ h: ["Qator qayerda ishlaydi", "Где ряд работает"],
      p: ["Darajali qator Σ cₙxⁿ har x da ham yaqinlashavermaydi — faqat |x| < R oraliqda. Σ aⁿxⁿ aslida maxraji q = ax bo'lgan geometrik qator: u |ax| < 1 da yaqinlashadi.",
        "Степенной ряд Σ cₙxⁿ сходится не при всех x — только при |x| < R. Σ aⁿxⁿ — это геометрический ряд со знаменателем q = ax: он сходится при |ax| < 1."] }],
    f: [{ n: ["Geometrik turdagi qator", "Ряд геометрического типа"], f: "Σ aⁿ·xⁿ:   R = 1 / |a|" }, { n: ["Umumiy formula", "Общая формула"], f: "R = lim |cₙ / cₙ₊₁|" }],
    s: [
      ["Koeffitsiyentni cₙ = aⁿ ko'rinishida yozing.", "Запишите коэффициент как cₙ = aⁿ."],
      ["|ax| < 1 shartini yozing.", "Запишите условие |ax| < 1."],
      ["|x| < 1/|a| — R shu.", "|x| < 1/|a| — это и есть R."],
    ],
    m: [{ s: ["Σ 4ⁿ·xⁿ.  R = ?", "Σ 4ⁿ·xⁿ.  R = ?"], y: ["|4x| < 1", "|x| < 1/4"], j: "1/4" }],
    x: [["R = a deb yozish. Koeffitsiyent qancha katta bo'lsa, radius shuncha KICHIK.", "Писать R = a. Чем больше коэффициент, тем МЕНЬШЕ радиус."]],
  },
  "oliy2|Makloren qatori": {
    t: [{ h: ["Funksiya — cheksiz ko'phad", "Функция — бесконечный многочлен"],
      p: ["Silliq funksiyani nol atrofida ko'phad bilan yaqinlashtirish mumkin: qancha ko'p had olinsa, shuncha aniq. eˣ uchun koeffitsiyentlar 1/n!; ko'rsatkichda ax tursa, har hadga aⁿ qo'shiladi.",
        "Гладкую функцию около нуля можно приблизить многочленом: чем больше членов, тем точнее. Для eˣ коэффициенты равны 1/n!; если в показателе ax, к каждому члену добавляется aⁿ."] }],
    f: [{ n: ["eˣ", "eˣ"], f: "eˣ = 1 + x + x²/2! + x³/3! + …" }, { n: ["e^(ax)", "e^(ax)"], f: "cₙ = aⁿ / n!" },
      { n: ["Faktorial", "Факториал"], f: "2! = 2,   3! = 6,   4! = 24" }],
    s: [
      ["a va n ni aniqlang.", "Определите a и n."],
      ["aⁿ va n! ni hisoblang.", "Вычислите aⁿ и n!."],
      ["Bo'lib, kasrni qisqartiring.", "Разделите и сократите дробь."],
    ],
    m: [{ s: ["e^(2x) = Σ cₙxⁿ.  c₃ = ?", "e^(2x) = Σ cₙxⁿ.  c₃ = ?"], y: ["2³ = 8,   3! = 6", "8 / 6"], j: "4/3" }],
    x: [["n! o'rniga n ga bo'lish: c₃ = 8/3 noto'g'ri, 8/6 to'g'ri.", "Делить на n вместо n!: c₃ = 8/3 неверно, верно 8/6."]],
  },

  /* ═══════════════════════ 2-kurs · differensial tenglamalar ═══════════════════════ */
  "oliy2|O'zgaruvchilari ajraladigan tenglamalar": {
    t: [{ h: ["y lar bir tomonga, x lar ikkinchisiga", "y в одну сторону, x — в другую"],
      p: ["y′ = dy/dx deb yozamiz va tenglamani shunday o'zgartiramizki, chapda faqat y va dy, o'ngda faqat x va dx qolsin. Keyin ikkala tomon alohida integrallanadi.",
        "Записываем y′ = dy/dx и преобразуем уравнение так, чтобы слева остались только y и dy, а справа — только x и dx. Затем обе части интегрируются отдельно."] }],
    f: [{ n: ["Ajratish", "Разделение"], f: "y′ = f(x)·y   ⇒   dy / y = f(x) dx" }, { n: ["Yechim", "Решение"], f: "ln |y| = ∫ f(x) dx + C   ⇒   y = C·e^(∫ f dx)" }],
    s: [
      ["dy/y = f(x) dx ko'rinishiga keltiring.", "Приведите к виду dy/y = f(x) dx."],
      ["O'ng tomonni integrallang.", "Проинтегрируйте правую часть."],
      ["y = C·e^(…) deb yozing.", "Запишите y = C·e^(…)."],
    ],
    m: [{ s: ["y′ = 4xy", "y′ = 4xy"], y: ["dy / y = 4x dx", "ln |y| = 2x² + C"], j: "y = Ce^(2x²)" }],
    x: [["∫ 4x dx = 4x² deb yozish — to'g'risi 2x².", "Писать ∫ 4x dx = 4x² — правильно 2x²."]],
  },
  "oliy2|Xarakteristik tenglama": {
    t: [{ h: ["Hosila o'rniga daraja", "Степень вместо производной"],
      p: ["y″ + py′ + qy = 0 tenglamaning yechimi e^(kx) ko'rinishida izlanadi. Uni tenglamaga qo'ysak, y″ → k², y′ → k, y → 1 bo'ladi va oddiy kvadrat tenglama chiqadi.",
        "Решение уравнения y″ + py′ + qy = 0 ищут в виде e^(kx). После подстановки y″ → k², y′ → k, y → 1 получается обычное квадратное уравнение."] }],
    f: [{ n: ["Xarakteristik tenglama", "Характеристическое уравнение"], f: "y″ + py′ + qy = 0   →   k² + pk + q = 0" },
      { n: ["Viyet", "Виет"], f: "k₁ + k₂ = −p,   k₁ · k₂ = q" }],
    s: [
      ["y″ ni k², y′ ni k, y ni 1 bilan almashtiring.", "Замените y″ на k², y′ на k, y на 1."],
      ["Kvadrat tenglamani yeching (Viyet yoki diskriminant).", "Решите квадратное уравнение (Виет или дискриминант)."],
      ["Ildizlarni o'sish tartibida yozing.", "Запишите корни по возрастанию."],
    ],
    m: [{ s: ["y″ − y′ − 6y = 0", "y″ − y′ − 6y = 0"], y: ["k² − k − 6 = 0", "k₁ + k₂ = 1,   k₁ · k₂ = −6"], j: "k₁ = −2,  k₂ = 3" }],
    x: [["Viyetda ishora: yig'indi −p ga teng, p ga emas.", "Знак в Виете: сумма равна −p, а не p."]],
  },
  "oliy2|Umumiy yechim": {
    t: [{ h: ["Ikki ildiz — ikki ko'rsatkichli funksiya", "Два корня — две экспоненты"],
      p: ["Xarakteristik tenglamaning ikki turli haqiqiy ildizi k₁ va k₂ bo'lsa, umumiy yechim ikkita ko'rsatkichli funksiyaning yig'indisi bo'ladi. C₁ va C₂ — ixtiyoriy o'zgarmaslar.",
        "Если характеристическое уравнение имеет два разных действительных корня k₁ и k₂, общее решение — сумма двух экспонент. C₁ и C₂ — произвольные постоянные."] }],
    f: [{ n: ["Umumiy yechim", "Общее решение"], f: "y = C₁·e^(k₁x) + C₂·e^(k₂x)" }, { n: ["y″ − a²y = 0", "y″ − a²y = 0"], f: "k = ±a" }],
    s: [
      ["Xarakteristik tenglamani yozing va yeching.", "Запишите и решите характеристическое уравнение."],
      ["Har ildiz uchun e^(kx) yozing.", "Для каждого корня запишите e^(kx)."],
      ["C₁ va C₂ bilan qo'shing.", "Сложите с C₁ и C₂."],
    ],
    m: [{ s: ["y″ − 9y = 0", "y″ − 9y = 0"], y: ["k² − 9 = 0  →  k = ±3"], j: "y = C₁e^(−3x) + C₂e^(3x)" }],
    x: [["Faqat bitta ildizni olish: k² = 9 dan k = 3 va k = −3.", "Взять только один корень: из k² = 9 следует k = 3 и k = −3."]],
  },

  /* ═══════════════════════ ehtimollar nazariyasi ═══════════════════════ */
  "ehtimollik|Kombinatsiya, o'rinlashtirish, o'rin almashtirish": {
    t: [{ h: ["Ikki savol formulani tanlaydi", "Два вопроса выбирают формулу"],
      p: ["1) Hamma element ishtirok etadimi? Ha — o'rin almashtirish (n!). 2) Tartib muhimmi? Muhim — o'rinlashtirish (A), muhim emas — kombinatsiya (C). \"Guruh tuzish\" — tartib yo'q; \"navbatga qo'yish\", \"rais va kotib saylash\" — tartib bor.",
        "1) Участвуют ли все элементы? Да — перестановки (n!). 2) Важен ли порядок? Важен — размещения (A), не важен — сочетания (C). «Составить группу» — порядка нет; «поставить в очередь», «выбрать председателя и секретаря» — порядок есть."] }],
    f: [{ n: ["O'rin almashtirish", "Перестановки"], f: "Pₙ = n!" },
      { n: ["O'rinlashtirish", "Размещения"], f: "Aₙᵏ = n! / (n − k)!" },
      { n: ["Kombinatsiya", "Сочетания"], f: "Cₙᵏ = n! / (k! · (n − k)!)" }],
    s: [
      ["Tartib muhimmi — aniqlang.", "Определите, важен ли порядок."],
      ["Formulani tanlang va n, k ni qo'ying.", "Выберите формулу и подставьте n, k."],
      ["Faktoriallarni qisqartirib hisoblang.", "Вычислите, сокращая факториалы."],
    ],
    m: [{ s: ["8 kishidan 3 kishilik guruh necha usulda tuziladi?", "Сколькими способами можно составить группу из 3 человек среди 8?"],
      y: ["Tartib muhim emas — C₈³", "8·7·6 / (3·2·1) = 336 / 6"], j: "56" }],
    x: [["Guruh uchun A ni ishlatish: javob k! marta katta chiqadi.", "Использовать A для группы: ответ получится в k! раз больше."]],
  },
  "ehtimollik|Klassik ehtimollik": {
    t: [{ h: ["Qulay hollar ulushi", "Доля благоприятных исходов"],
      p: ["Hamma natija teng imkoniyatli bo'lsa, ehtimollik — qulay natijalar sonining jami natijalar soniga nisbati. Ikki zar tashlanganda jami 6 · 6 = 36 natija bor.",
        "Если все исходы равновозможны, вероятность — отношение числа благоприятных исходов к общему числу. При броске двух костей всего 6 · 6 = 36 исходов."] }],
    f: [{ n: ["Klassik ta'rif", "Классическое определение"], f: "P(A) = m / n" }, { n: ["Chegaralar", "Границы"], f: "0 ≤ P ≤ 1" }],
    s: [
      ["Jami natijalar sonini toping (n).", "Найдите общее число исходов (n)."],
      ["Qulay natijalarni sanab chiqing (m).", "Перечислите благоприятные исходы (m)."],
      ["m / n ni qisqartiring.", "Сократите m / n."],
    ],
    m: [{ s: ["Ikki zar tashlandi. Yig'indi 9 bo'lish ehtimoli?", "Брошены две кости. Вероятность суммы 9?"],
      y: ["n = 36", "(3;6), (4;5), (5;4), (6;3) — m = 4", "4 / 36"], j: "1/9" }],
    x: [["(4;5) va (5;4) ni bitta hol deb sanash — zarlar har xil, bu ikki hol.", "Считать (4;5) и (5;4) одним исходом — кости разные, это два исхода."]],
  },
  "ehtimollik|Ehtimollarni ko'paytirish": {
    t: [{ h: ["\"Va\" — ko'paytirish", "«И» — умножение"],
      p: ["Ikki hodisa birga ro'y berishi ehtimoli — birinchisining ehtimoli ko'paytirilgan ikkinchisining (birinchisi ro'y bergandan keyingi) ehtimoliga. Qaytarmasdan olinganda idishdagi sharlar kamayadi — ikkinchi kasr o'zgaradi.",
        "Вероятность того, что произойдут оба события, — вероятность первого, умноженная на вероятность второго (при условии, что первое произошло). При выборе без возвращения шаров становится меньше — вторая дробь меняется."] }],
    f: [{ n: ["Ko'paytirish teoremasi", "Теорема умножения"], f: "P(A va B) = P(A) · P(B | A)" }],
    s: [
      ["Birinchi olishning ehtimolini yozing.", "Запишите вероятность первого извлечения."],
      ["Sharlar sonini kamaytiring va ikkinchisini yozing.", "Уменьшите число шаров и запишите вторую."],
      ["Ko'paytirib qisqartiring.", "Перемножьте и сократите."],
    ],
    m: [{ s: ["Idishda 3 oq, 2 qora shar. 2 ta qaytarmasdan olindi — ikkalasi oq?", "В урне 3 белых, 2 чёрных. Вынуты 2 без возврата — оба белые?"],
      y: ["Birinchisi oq: 3/5", "Ikkinchisi oq: 2/4", "3/5 · 2/4 = 6/20"], j: "3/10" }],
    x: [["Ikkinchi olishda ham 3/5 yozish — bitta oq shar allaqachon olingan.", "Писать 3/5 и для второго извлечения — один белый шар уже вынут."]],
  },
  "ehtimollik|To'la ehtimollik formulasi": {
    t: [{ h: ["Har yo'l bo'yicha, keyin qo'shish", "По каждому пути, затем сложить"],
      p: ["Hodisa bir necha yo'l bilan ro'y berishi mumkin bo'lsa (birinchi idishdan yoki ikkinchisidan), har yo'lning ehtimoli alohida hisoblanadi — yo'lni tanlash ehtimoli ko'paytirilgan shu yo'ldagi natija ehtimoliga — va hammasi qo'shiladi.",
        "Если событие может произойти несколькими путями (из первой урны или из второй), вероятность каждого пути считается отдельно — вероятность выбрать путь, умноженная на вероятность исхода на нём, — и всё складывается."] }],
    f: [{ n: ["To'la ehtimollik", "Полная вероятность"], f: "P(A) = P(H₁)·P(A | H₁) + P(H₂)·P(A | H₂)" }],
    s: [
      ["Gipotezalar ehtimolini yozing (tasodifiy idish — 1/2 dan).", "Запишите вероятности гипотез (случайная урна — по 1/2)."],
      ["Har idishda oq shar ulushini toping.", "Найдите долю белых шаров в каждой урне."],
      ["Ko'paytirib qo'shing.", "Перемножьте и сложите."],
    ],
    m: [{ s: ["1-idish: 2 oq, 2 qora. 2-idish: 3 oq, 1 qora. Tasodifiy idishdan shar — oq?", "1-я урна: 2 белых, 2 чёрных. 2-я: 3 белых, 1 чёрный. Шар из случайной урны — белый?"],
      y: ["1/2 · 2/4 = 1/4", "1/2 · 3/4 = 3/8", "1/4 + 3/8 = 2/8 + 3/8"], j: "5/8" }],
    x: [["Idishni tanlash ehtimolini (1/2) unutib, faqat 2/4 + 3/4 ni qo'shish — natija 1 dan katta chiqadi.", "Забыть вероятность выбора урны (1/2) и сложить только 2/4 + 3/4 — получится больше 1."]],
  },
  "ehtimollik|Bernulli sxemasi": {
    t: [{ h: ["Bir xil tajriba n marta", "Один и тот же опыт n раз"],
      p: ["Tajriba n marta mustaqil takrorlanadi, har safar muvaffaqiyat ehtimoli p. Aynan k marta muvaffaqiyat bo'lishi uchun: qaysi k tasida ekanini tanlash usullari soni (C) ko'paytiriladi bitta shunday ketma-ketlik ehtimoliga.",
        "Опыт независимо повторяется n раз, вероятность успеха каждый раз p. Для ровно k успехов: число способов выбрать, в каких k опытах (C), умножается на вероятность одной такой последовательности."] }],
    f: [{ n: ["Bernulli formulasi", "Формула Бернулли"], f: "Pₙ(k) = Cₙᵏ · pᵏ · (1 − p)ⁿ⁻ᵏ" }, { n: ["Tanga uchun", "Для монеты"], f: "Pₙ(k) = Cₙᵏ / 2ⁿ" }],
    s: [
      ["n, k va p ni aniqlang.", "Определите n, k и p."],
      ["Cₙᵏ ni hisoblang.", "Вычислите Cₙᵏ."],
      ["pᵏ(1 − p)ⁿ⁻ᵏ ga ko'paytiring.", "Умножьте на pᵏ(1 − p)ⁿ⁻ᵏ."],
    ],
    m: [{ s: ["Tanga 4 marta tashlandi. Gerb aynan 2 marta tushishi?", "Монета брошена 4 раза. Герб выпал ровно 2 раза?"],
      y: ["C₄² = 6", "2⁴ = 16", "6 / 16"], j: "3/8" }],
    x: [["Cₙᵏ ni unutib, faqat (1/2)ⁿ yozish — bu BITTA aniq ketma-ketlikning ehtimoli.", "Забыть Cₙᵏ и написать только (1/2)ⁿ — это вероятность ОДНОЙ конкретной последовательности."]],
  },
  "ehtimollik|Matematik kutilma": {
    t: [{ h: ["Vaznli o'rtacha", "Взвешенное среднее"],
      p: ["Matematik kutilma — tasodifiy miqdorning uzoq muddatdagi o'rtacha qiymati. Har qiymat o'z ehtimoliga ko'paytiriladi va natijalar qo'shiladi: tez-tez chiqadigan qiymat o'rtachaga ko'proq ta'sir qiladi.",
        "Математическое ожидание — среднее значение случайной величины на длинной дистанции. Каждое значение умножается на свою вероятность, результаты складываются: частое значение влияет на среднее сильнее."] }],
    f: [{ n: ["Kutilma", "Ожидание"], f: "M(X) = x₁p₁ + x₂p₂ + … + xₙpₙ" }, { n: ["Tekshiruv", "Проверка"], f: "p₁ + p₂ + … + pₙ = 1" }],
    s: [
      ["Ehtimollar yig'indisi 1 ekanini tekshiring.", "Проверьте, что сумма вероятностей равна 1."],
      ["Har qiymatni o'z ehtimoliga ko'paytiring.", "Умножьте каждое значение на его вероятность."],
      ["Ko'paytmalarni qo'shing.", "Сложите произведения."],
    ],
    m: [{ s: ["X: 1; 4; 10    P: 0,5; 0,3; 0,2.  M(X) = ?", "X: 1; 4; 10    P: 0,5; 0,3; 0,2.  M(X) = ?"],
      y: ["1·0,5 = 0,5;   4·0,3 = 1,2;   10·0,2 = 2", "0,5 + 1,2 + 2"], j: "3,7" }],
    x: [["Qiymatlarning oddiy o'rtachasini olish ((1 + 4 + 10)/3) — ehtimollar teng emas.", "Брать обычное среднее ((1 + 4 + 10)/3) — вероятности не равны."]],
  },
  "ehtimollik|Binomial taqsimot": {
    t: [{ h: ["Muvaffaqiyatlar soni", "Число успехов"],
      p: ["n ta mustaqil tajribadagi muvaffaqiyatlar soni binomial taqsimotga ega. Uning o'rtachasi sodda: tajribalar soni ko'paytirilgan bitta tajribadagi ehtimolga. Dispersiya esa np ga yana (1 − p) qo'shiladi.",
        "Число успехов в n независимых опытах имеет биномиальное распределение. Его среднее простое: число опытов, умноженное на вероятность в одном опыте. В дисперсии к np добавляется множитель (1 − p)."] }],
    f: [{ n: ["Kutilma", "Ожидание"], f: "M(X) = n · p" }, { n: ["Dispersiya", "Дисперсия"], f: "D(X) = n · p · (1 − p)" }],
    s: [
      ["Nima so'ralganini aniqlang: M yoki D.", "Определите, что требуется: M или D."],
      ["n · p ni hisoblang.", "Вычислите n · p."],
      ["D uchun yana (1 − p) ga ko'paytiring.", "Для D умножьте ещё на (1 − p)."],
    ],
    m: [{ s: ["n = 40,  p = 1/4.  M(X) = ?", "n = 40,  p = 1/4.  M(X) = ?"], y: ["40 · 1/4"], j: "10" }],
    x: [["M va D ni almashtirib yuborish: M da (1 − p) yo'q.", "Перепутать M и D: в M нет множителя (1 − p)."]],
  },
  "ehtimollik|Tanlanma xarakteristikalari": {
    t: [{ h: ["Ma'lumotni bitta son bilan", "Данные одним числом"],
      p: ["O'rta qiymat — yig'indi bo'linadi soniga. Mediana — tartiblangan qatorning o'rtadagi qiymati (juft sonda — ikki o'rtadagining o'rtachasi). Kenglik — eng katta va eng kichik qiymat farqi.",
        "Среднее — сумма, делённая на количество. Медиана — срединное значение упорядоченного ряда (при чётном числе — среднее двух срединных). Размах — разность наибольшего и наименьшего."] }],
    f: [{ n: ["O'rta qiymat", "Среднее"], f: "x̄ = (x₁ + x₂ + … + xₙ) / n" }, { n: ["Kenglik", "Размах"], f: "R = x_max − x_min" }],
    s: [
      ["Mediana uchun AVVAL sonlarni o'sish tartibida yozing.", "Для медианы СНАЧАЛА запишите числа по возрастанию."],
      ["O'rtadagi sonni toping.", "Найдите срединное число."],
      ["O'rta qiymat uchun — qo'shib, soniga bo'ling.", "Для среднего — сложите и разделите на количество."],
    ],
    m: [{ s: ["7, 3, 9, 3, 5  →  Me = ?", "7, 3, 9, 3, 5  →  Me = ?"], y: ["Tartiblaymiz: 3, 3, 5, 7, 9", "O'rtadagi — uchinchi son"], j: "5" }],
    x: [["Tartiblamasdan o'rtadagi sonni olish (bu yerda 9 chiqardi).", "Брать срединное число без упорядочивания (здесь получилось бы 9)."]],
  },
};
